### ISSUE TITLE
Unable to run app in Android Studio until "Instant Run" disabled

### ISSUE THREAD

**Issue by WhatDoYouKnow** [NordicSemiconductor/Android-BLE-Library#101]
Hi
Just trying to run an app for BLE and the Blinky app kept stopping without getting started.
Found another github project which suggested disabling "Instant Run" (File > Settings > Build, Execution, Deployment > Instant Run).
Doing this allowed nRF Blinky to run in my environment. Add this to the front page?
Thanks

**Comment by WhatDoYouKnow** [comment]
Error message starts with: Didn't find class "androidx.lifecycle.ProcessLifecycleOwnerInitializer" on path:
Frustrating until this simple change fixed it.

**Comment by philips77** [comment]
Thanks, I'll add it to the Readme.

**Comment by JohnIDPal** [comment]
Hi, unable to run this app in android studio. Can you please set the missing files in the mainfest

**Comment by philips77** [comment]
This is not an app, it's a library. Please, check out https://github.com/NordicSemiconductor/Android-nRF-Blinky for how to use it in an app.

**Comment by philips77** [comment]
Instant Run is no longer a thing. Closing the issue.
