### ISSUE TITLE
BleManager Internal Connect 

### ISSUE THREAD

**Issue by JamesDougherty** [NordicSemiconductor/Android-BLE-Library#107]
Hello Aleksander,

Hope all has been well. We have had several bug reports, one in beta and now one in production, pointing to the same place so I wanted to bring it to your attention.

The stack trace below was for version 2.1.0 of the library and the source has changed in the most recent commit you have (it's line 825 in the most recent commit).

`mGattCallback.setHandler(mHandler);`

I looked the first time I got this exception and I'm not 100% sure how it's happening and it makes it hard to pinpoint as it doesn't always happen. Somehow `mGattCallback` is NULL when the above line gets called in the `internalConnect` method. `mGattCallback` gets initialized when the `enqueue` method gets called the first time. So if no methods get called that require `enqueue` before connection then it crashes here. That is what's confusing me because the connection call itself requires the `enqueue`...

```java
if (!mBluetoothIsClassic && mBleManager != null && mSelectedValve != null) {
    mBleManager.connect(mSelectedValve.getBluetoothDevice())
               .usePreferredPhy(PhyRequest.PHY_LE_1M_MASK | PhyRequest.PHY_LE_2M_MASK)
               .retry(5, 200)
               .fail((device, status) -> {
                   if (status == FailCallback.REASON_DEVICE_DISCONNECTED) {
                       reconnect();
                   }
               })
               .invalid(() -> CsLog.bluetooth("Invalid Request"))
               .useAutoConnect(false)
               .enqueue();
}
```

To test this theory I created a simple temporary workaround that may work? Not sure.
```java
public final class CsBleManager extends BleManager<BleManagerCallbacks> {
    public CsBleManager(@NonNull Context context, final CsBluetoothEventCallbacks eventCallbacks) {
        super(context);
        mEvents = eventCallbacks;

        //Workaround for the mGattCallback being NULL in the BleManger class? This needs tested to make sure.
        sleep(1).enqueue();
    }
}
```

Any ideas would be greatly appreciated.

```
Alco Voyager Pro (RCT6873W42BMF8KC), Android 8.1

java.lang.NullPointerException: 
  at no.nordicsemi.android.ble.BleManager.internalConnect (BleManager.java:821)
  at no.nordicsemi.android.ble.BleManager.access$2100 (BleManager.java:113)
  at no.nordicsemi.android.ble.BleManager$BleManagerGattCallback.lambda$onConnectionStateChangeSafe$1 (BleManager.java:2466)
  at no.nordicsemi.android.ble.-$$Lambda$BleManager$BleManagerGattCallback$bwdQL5hRHEL3hHIRT5Ny7ZfRBIM.run (-.java:4)
  at android.os.Handler.handleCallback (Handler.java:790)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6523)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:857)
```

**Comment by JamesDougherty** [comment]
Hello - This has now happened 8 total times. Here are a list of devices as an FYI:

1) Google Pixel XL (marlin), Android 9
2,3) Samsung Galaxy Note8 (greatqlte), Android 9 (two reports)
4) OnePlus OnePlus5 (OnePlus5), Android 9
5) Samsung Galaxy S7 (heroqltevzw), Android 8.0
6) Samsung Galaxy S5 (klteatt), Android 6.0
7) Samsung Galaxy S9+ (star2qlteue), Android 9
8) Alco Voyager Pro (RCT6873W42BMF8KC), Android 8.1

**Comment by JamesDougherty** [comment]
I just wanted to follow-up on this. It's happening way too much (about 20 times a month).

**Comment by kiafaldorius** [comment]
Using the direct Ble API calls from android without this library also gives me sporadic GATT errors when attempting to connect using Coded PHY, so I'd like to also see what's going on if anyone has any clues.

**Comment by philips77** [comment]
Hello,
So sorry for very late response, I missed your issue. I released several versions since you created the issue, latest one being 2.2.1 released today. Did you manage to solve your problem? Did you migrate to 2.2.x and observed an improvement?

**Comment by JamesDougherty** [comment]
Hello,

It's OK. I'm not sure how well my workaround actually worked because it has crashed 25 times in the last 60 days due to this. I will update the library on the next release and let you know. I'm on a different project at the moment so it may not be updated for a while unless we run into something else.

Appreciate it.

**Comment by philips77** [comment]
I'm closing the issue due to inactivity.
