### ISSUE TITLE
Connection with Nordic UART device is not working on Android 7.1

### ISSUE THREAD

**Issue by fabianenye** [NordicSemiconductor/Android-BLE-Library#11]
I have a Motorola G5S with Android 7.1. The Nordic NRF Toolbox app and the NRF Connect and also this library, disconnects automatically inmediately after it connects. I cannot establish a connection. In Android 7.0 it works. Does it make sense?

**Comment by sivapraka** [comment]
I have also faced the same issue

**Comment by philips77** [comment]
Hi, sorry for the super long delay. Do you still face this issue? Did you try v2 of the BLE library?

**Comment by hyoungtaikkim** [comment]
Hi,

In my case, Android 8.0 doesn't work for the matter of connection. I think that, in BLE manager,

mBluetoothGatt = device.connectGatt(mContext, false, mGattCallback = getGattCallback());

should be changed to 

mBluetoothGatt = device.connectGatt(mContext, false, mGattCallback = getGattCallback(), 2); 

especially for newer OS.

**Comment by philips77** [comment]
The new version of the library uses TRANSPORT_LE for Marshmallow or newer: https://github.com/NordicSemiconductor/Android-BLE-Library/blob/master/ble/src/main/java/no/nordicsemi/android/ble/BleManager.java#L805. Actually, the `connectGatt` with `transport` parameter was available before (since KitKat?), but only using reflections.

**Comment by hyoungtaikkim** [comment]
Hi,

Thank you very much for your work again. Anyway I have tried the library 2.0, but there was some connection issue again for Android 8.0, LG phone. So I have gone back to 1.2 version with the above change I have commented in the above. So no connection problem in my case after the change. So I would like to recommend you to test the library 2.0 with Android 8.0 (Oreo).

Thanks again.
