### ISSUE TITLE
Reason for disconnect is unknown

### ISSUE THREAD

**Issue by sssemil** [NordicSemiconductor/Android-BLE-Library#110]
It's impossible to know the reason for device disconnect. Would it be possible to implement some sort of internal mapping of the Android's GATT errors/states, that is passed along with the 'onDeviceDisconnected' call? Here are some examples of reasons: user disconnected on the remote device, user disconnected on the local device, connection timed out, etc. Or generally speaking it would be nice be able to distinguish intentional and unintentional disconnects.

Related https://github.com/NordicSemiconductor/Android-BLE-Library/pull/21.

**Comment by pblitz** [comment]
maybe we can actually support and do a PR for this. Any preference on how to do this? Adding a parameter to onDeviceDisconnected will break the API. Is that okay? 
Or should we add a onDeviceDisconnectedWithReason() (that looks horrible tho :/ )

**Comment by philips77** [comment]
I guess I would add another Reason in FailCallback for disconnection initiated by remote device leaving the current status -1 for locally initiated. Timeout already has it's reason. This also includes adding a new Exception for synchronous calls. Indeed send like a breaking change, so would increase version to at least 2.2, but worth doing.
