### ISSUE TITLE
How can i get the timeout for connect?

### ISSUE THREAD

**Issue by hjh2881** [NordicSemiconductor/Android-BLE-Library#125]
How can i know ,the connection is timeout?

**Comment by philips77** [comment]
There is a [timeout()](https://github.com/NordicSemiconductor/Android-BLE-Library/blob/5e0e2f08c309a6de2376d9b8705c83f9e9a80d56/ble/src/main/java/no/nordicsemi/android/ble/TimeoutableRequest.java#L58) method in the `ConnectRequest`.

**Comment by hjh2881** [comment]
Thank you
