### ISSUE TITLE
Android-BLE-Library not working properly

### ISSUE THREAD

**Issue by dominicbar** [NordicSemiconductor/Android-BLE-Library#127]
after updating ble library 2.1.1, mesh services are not getting detected(giving null), so after provisioning phone thinks the bluetooth device is still unprovsioned,
Note that this issue happens for xiaomi redmi note 3 device

In nrf mesh we upgraded the android BLE library to 2.1.1, we could reproduce the issue there also
Provisioning happens properly, only configuration dosen't happen only for redmi note 3 devices

![WhatsApp Image 2019-09-11 at 11 25 31 AM](https://user-images.githubusercontent.com/51821391/64690990-590e8580-d4af-11e9-8ff4-953012981244.jpeg)

**Comment by roshanrajaratnam** [comment]
@dominicbar Since you have upgraded the the library, I suppose you need to refresh the Gatt cache, if not Android will use cached services from the first connection.

**Comment by dominicbar** [comment]
We did the above, most of the phones its working, but 2 xiaomi redmi note 3 are giving the same problem

**Comment by dominicbar** [comment]
but ya once we downgrade the ble library, the redmi note 3 phone works fine

**Comment by roshanrajaratnam** [comment]
What you may also do is set up retry events, so the device will try to connect multiple times which is supported on the latest BLE Library

**Comment by philips77** [comment]
Hi, could you post here logs from the BLE Library 2.x during the connection? Override the `log` method in the `BleManager`. Let's see what is going on there.

**Comment by philips77** [comment]
Hi, we have migrated nRF Mesh to Android BLE Library 2.1.1 and fixed all the issues. Please, take a look at them. All should be working now.
