### ISSUE TITLE
Quick disable and enable notify on the same characteristics in succession doesn't work 

### ISSUE THREAD

**Issue by uberchilly** [NordicSemiconductor/Android-BLE-Library#136]
When I enqueue disableNotifications and then enqueue enableNotifications in succession for the same characteristic I can see it does these operations on the embedded device but DataReceivedCallback doesn't receive any more data from that point. I also receive SuccessCallback for both disable and enable operations. 

More context: 
My plan is to make every fragment responsible for managing its own notifications to enable them on start and disable them on stop. I have 2 fragments, but 1 characteristic is listened on both fragments. That is how I get into the situation where I disableNotifications on the first one and very quickly afterwards enable it again on different screen because of how fragment lifecycle in android works when user switches screens. 
When I add some arbitrary timeout of 1 second, for example, before enableNotifications call helps, everything works then. 

Any insight on why I don't receive data? 

Images below just shows how I setup enable and disable operations  
![image](https://user-images.githubusercontent.com/5727941/69482017-82844f80-0e16-11ea-9963-e2664461cdbc.png)
![image](https://user-images.githubusercontent.com/5727941/69482024-929c2f00-0e16-11ea-883d-464032fdb290.png)

**Comment by philips77** [comment]
Perhaps the notification listener gets removed on disabling notifications? Food you try setting it again before enabling?

**Comment by philips77** [comment]
Have a look at this line:
https://github.com/NordicSemiconductor/Android-BLE-Library/blob/5e0e2f08c309a6de2376d9b8705c83f9e9a80d56/ble/src/main/java/no/nordicsemi/android/ble/BleManager.java#L2795

**Comment by philips77** [comment]
To re-set the callbacks, set them in `done` after they are actually disabled.

**Comment by uberchilly** [comment]
I have moved data callback into onDone callback, now it works. I am missing some data that is triggered immediately from the device though, but setting callback before enable and inside onDone fixes that issue as well. 
Tnx, closing the issue.
