### ISSUE TITLE
Error disconnected before try pairing 

### ISSUE THREAD

**Issue by KORuL** [NordicSemiconductor/Android-BLE-Library#137]
For some reason, it is determined that the device is not paired, but it is called ondonnected without trying to pair. Glucometer - one touch select plus flex

**Comment by philips77** [comment]
The library will not try to pair by itself. You have to call `createBond().enqueue()` to initiate pairing or read/write protected attribute (characteristic or descriptor).

**Comment by KORuL** [comment]
BleManager should perform a pairing automatically, this does not happen
