### ISSUE TITLE
NRF ToolBox UART De-Bugging.

### ISSUE THREAD

**Issue by StudyMaterialsAndProjects** [NordicSemiconductor/Android-BLE-Library#146]
Hi ,
frist of all thanks for providing the source for this application.[NRF Toolbox](https://github.com/NordicSemiconductor/Android-nRF-Toolbox).

Here i am De-Bugging the application for the UART in that i am seeing a Connection is done using
Google API.(Screen Shot i have attached).
![Capture](https://user-images.githubusercontent.com/59191091/71815104-65dd6780-30a4-11ea-99bf-7f0eacd6696f.PNG)

But the documentation says that UART is using below code to do the connection.[Link](https://github.com/NordicSemiconductor/Android-BLE-Library)
![Capture1](https://user-images.githubusercontent.com/59191091/71815161-958c6f80-30a4-11ea-9091-5afd7b12d2b6.PNG)

which is the actually right...?

can you please provide the code where the BLE library is used...
so that it will be easy to De-Bug.

**Comment by philips77** [comment]
Have a look at UARTManager`` class. The Google API here is used to connect to Wear devices, which can also be used to send UART commands in nRF Toolbox. This feature is optional and we are not sure if it still works on Google Wear watches, as the sample app we made is very old now.

**Comment by VinayTShetty** [comment]
Hi philips,
i want to connect,read write and notify data from BLE device.
i am looking for a simple example.which uses **Android-BLE-Library**,can you please tell me where i can get this..
Thanks in Advance.

**Comment by philips77** [comment]
Have a look at [nRF Blinky](https://github.com/NordicSemiconductor/Android-nRF-Blinky).
