### ISSUE TITLE
Initialize app problem 

### ISSUE THREAD

**Issue by NimaaZx** [NordicSemiconductor/Android-BLE-Library#163]
Hello. 
at first I don't know that I am at right place or not. Please Guide me. I want to use scanner BLE for android phone [version from 5 or 6 up to latest 9 or 10 or every version that will be released later].
1- I just want to scan RSSI value from BLE modules like wristband ble and filter their specific MAC then convert rssi to distance or at lease report them about near or far   
2- I need run it as a service when user change fragment , it must work until the user stops it or app closed (onDestroy). 

is this library suitable for me ?
I felt it does more things that I want. :)

how ever I wanted to implement this lib from example guide. I tried to define a class that you wrote in README file . at first I wanted to convert them to Kotlin. because I started android programming with Kotlin. I did not do that and I went with java. but some variables are not recognized at all . can not resolve.

 what do i do ? 
I write all of them for you:

dataCharacteristic in :
```java
if (firstCharacteristic != null) {
    final int properties = dataCharacteristic.getProperties();
    notify = (properties & BluetoothGattCharacteristic.PROPERTY_NOTIFY) != 0;
}
```

controlPointCharacteristic in :

```java
final int properties = controlPointCharacteristic.getProperties();
writeRequest = (properties & BluetoothGattCharacteristic.PROPERTY_WRITE) != 0;
```

callback in :
```java
setNotificationCallback(firstCharacteristic, callback);
```

FluxJumpRequest & INDO & callbacks & write in:

```java
    public void enableFluxCapacitor(final int year) {
        waitForNotification(firstCharacteristic)
                .trigger(
                        writeCharacteristic(secondCharacteristic, new FluxJumpRequest(year))
                                .done(device -> log(Log.INDO, "Power on command sent"))
                )
                .with(new FluxHandler() {
                    public void onFluxCapacitorEngaged() {
                        log(Log.WARN, "Flux Capacitor enabled! Going back to the future in 3 seconds!");
                        callbacks.onFluxCapacitorEngaged();

                        sleep(3000).enqueue();
                        write(secondCharacteristic, "Hold on!".getBytes())
                                .done(device -> log(Log.WARN, "It's " + year + "!"))
                                .fail((device, status) -> "Not enough flux? (status: " + status + ")")
                                .enqueue();
                    }
                })
                .enqueue();
```
cancelQueue () in :
```java
    public void abort() {
        cancelQueue();
    }
```

**Comment by philips77** [comment]
The sample in Readme uses an example service and characteristics. You need to change them to your in the device you connect to, assuming you do want to connect to the device.
Use nRF Connect app to find your what services your wrist band has and use those uuids in your app, if you need to send it read any date other than rssi.

**Comment by philips77** [comment]
Have a look at nRF Blinky sample app on GitHub. You'll find there BlinkyManager.

**Comment by NimaaZx** [comment]
> Have a look at nRF Blinky sample app on GitHub. You'll find there BlinkyManager.

Oh. Thank you for your concern. I do not want  connect to my ble wristband. I just what scanning, filters, do some calculations. 

1- You mean I should implement something that I need not everything?

Yesterday I could use own default android ble library for doing that things I wanted. 

2-Could you tell me what is the difference between NordicSemiConductor library and that default library in android ? 
What capabilities or extras...

**Comment by philips77** [comment]
For scanning only, you should use the scanner API, not this library. If you want your app to support Android 4.3+, not only the latest Android versions, we recommend checking on https://github.com/NordicSemiconductor/Android-Scanner-Compat-Library. The scanner compat lib tries to emulate the new features and API on older Android versions, so you won't need to write duplicate code (scanner API has changed in Android 5 and was extended later).

The BLE Library is a handy lib for handling connections. It has more readable API than the native one, handles some common errors and separates Bluetooth low-level implementation from the high-level device API.
