### ISSUE TITLE
MTU change from peripheral question

### ISSUE THREAD

**Issue by XabierGoros** [NordicSemiconductor/Android-BLE-Library#164]
If a MTU negotiation is only performed by the peripheral, the `onMtuChanged` method is not invoked. According to your documentation, in that case, `android.bluetooth.BluetoothGattServerCallback#onMtuChanged(BluetoothDevice, int)` should be used instead. However,  the following method in `MainThreadBluetoothGattCallback` which extends from `BluetoothGattCallback` is not invoked either:

```java
@RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
@Override
public final void onMtuChanged(@NonNull final BluetoothGatt gatt,
  			       @IntRange(from = 23, to = 517) final int mtu, final int status) {
	runOnUiThread(() -> onMtuChangedSafe(gatt, mtu, status));
}
```

Isn't it possible to get the negotiated MTU without requesting a change?

**Comment by philips77** [comment]
Observe the "Server" in `BluetoothGattServerCallback`. Only the server callback will get MTU update when initiated by remote side.
You may use BLE Library version 2.2.0 (currently alpha 6), where you can also set up the gatt server and get this callback.
