### ISSUE TITLE
It would be nice if the same kind of UUID object was used between this and scanning

### ISSUE THREAD

**Issue by travisgriggs** [NordicSemiconductor/Android-BLE-Library#167]
I've started using the Android Scanner Compat Library and have been pleased with it so far. So I wanted to switch to use this for my GATT interactions. I believe there's some overlap between both teams? For my scanner interaction, the code wants me to a ParcelUuid for service:

    val UUIDMainService = ParcelUuid.fromString("00000000-08af-41c0-8048-4e454c534f4e")

But the gatt interface seems to prefer

     val UUIDMainService = UUID.fromString("00000000-08af-41c0-8048-4e454c534f4e") 

Any reason to have companion libraries use different UUID types?

**Comment by philips77** [comment]
Hi,
The difference between `ParcelUuid` and `UUID` is that the first one wraps the other and implements `Parcelable` interface, so the UUID can be sent to scanning service, e.g. using `PendingIntent`. The scanner combat library aimed to have the same API as the original Android API, and as you can see here: https://developer.android.com/reference/android/bluetooth/le/ScanFilter.Builder the `ScanFilter` class uses parcelable version.
However, the GATT objects, like services, characteristics and descriptors use normal UUIDs: https://developer.android.com/reference/android/bluetooth/BluetoothGattService.

You may also create `ParcelUuid` from the normal UUID using https://developer.android.com/reference/android/os/ParcelUuid#ParcelUuid(java.util.UUID).
