### ISSUE TITLE
Connection Handling like iOS

### ISSUE THREAD

**Issue by WuLFGit** [NordicSemiconductor/Android-BLE-Library#171]
Hi,

Since i know that on iOS side your SDK holds up multiple connections at a time, eventually saving new scan&connect operations, there is any chance we will have the same feature on the Android side? If yes, there's already a release date?

I'm asking because even with your latest stable BLE version 2.1.4 i'm still facing connection issues resulting in status codes 133 that was not resolved as expected. I would like to save connection operations like iOS does in the background.

Thank you

**Comment by philips77** [comment]
Android also supports multiple simultaneous connections, I think up to 6 or 8, perhaps more on modern phones. By using this library, you have one `BleManager` instance per device. Have a look at [nRF Toolbox](https://github.com/NordicSemiconductor/Android-nRF-Toolbox) -> Proximity profile, which allows to connect to multiple tags. 

I have no idea what do you mean by:
- handling connection like iOS - does Android do it differently? What do you mean?
- save connection operations like iOS
- what our SDK on iOS side?

Regarding error 133 I replied to you in #170.
