### ISSUE TITLE
Was there no callback when the automatic reconnection succeeded?

### ISSUE THREAD

**Issue by fuhaodev** [NordicSemiconductor/Android-BLE-Library#176]
Hello, I upgraded to alpha08 and did not find a callback when the automatic reconnection succeeded，

**Comment by philips77** [comment]
I spent very little time on testing the recent alphas. If you have any comments, please write. I'm planning to release final version quite soon. Thank you for testing!

**Comment by philips77** [comment]
Btw, have you found it in alpha09?

**Comment by fuhaodev** [comment]
Thanks for your reply, I found it in alpha10
