### ISSUE TITLE
Bluetooth broadcast 100ms

### ISSUE THREAD

**Issue by Deepblue1996** [NordicSemiconductor/Android-BLE-Library#219]
Bluetooth broadcast mode can only set the low delay of 100ms. Is there any way to set the lower delay

**Comment by philips77** [comment]
I believe you are talking about [setAdvertiseMode(...)](https://developer.android.com/reference/android/bluetooth/le/AdvertiseSettings.Builder#setAdvertiseMode(int)) or [setInterval(...)](https://developer.android.com/reference/android/bluetooth/le/AdvertisingSetParameters.Builder#setInterval(int)).
As the documentation says, the lowest interval is 100 ms.

This library does not support Bluetooth LE advertising.
