### ISSUE TITLE
Cannot receive notification. Is it related to uuid?

### ISSUE THREAD

**Issue by Serobegi** [NordicSemiconductor/Android-BLE-Library#220]
Hello!
i'm now using nordic device. but 

I want to communicate with the Nordic device I am using.

However, when writing data in the Android app, read or notification does not come.

The uuid I use is:

-Service-
`private static final UUID SWITCH_GATT_SERVICE_UUID = UUID.fromString("0003cdd0-0000-1000-8000-00805f9b34fb");`

  -Characteristic (Write & Write no reponse)
`private static final UUID SWITCH_GATT_CHARACTERISTIC_UUID = UUID.fromString("0003cdd1-0000-1000-8000-00805f9b34fb");`

-Notify-
`private static final UUID SWITCH_GATT_NOTIFICATION_UUID = UUID.fromString("0003cdd2-0000-1000-8000-00805f9b34fb");`

Descriptros
`UUID 0x2902`

How can I get ACk for the data I send?

Thank you

**Comment by philips77** [comment]
Hello,
Please read the Bluetooth LE spec or any tutorial. You need to enable notifications on the server and the server needs to send them. I don't know what you are doing at the moment and what does your device do. To read the data, your characteristic needs Read property, and most importantly Read permission on the server side.

Also, avoid using standard Bluetooth Base UUID for your custom UUIDs. The ones you have match 32-bit UUID which are reserved for Bluetooth SIG. It's much better to just randomize the entire UUID.
