### ISSUE TITLE
Unable to disconnect when ConnectRequest is processing.

### ISSUE THREAD

**Issue by shiehnpin** [NordicSemiconductor/Android-BLE-Library#221]
Hi there,

I'm facing the behaviour that I'm not sure whether is the limitation or the issue.  Firstly, I invoke a connect request to the device which isn't there at the time. Then I call disconnect() after the connect request is enqueued. But no matter how the disconnect request is invoked by await() or enqueue(), the process is postponed until the connect request timeout. 

My question is: Is it not allowed to disconnect while the connecting is processing?

Mobile: Pixel 3a
Library version: 2.2.3

**Comment by philips77** [comment]
Currently there is no abort feature in any of the requests. But this seems to be a valid use case. I'll add this to the backlog.

**Comment by philips77** [comment]
Task: Add `abort()` method to `ConnectRequest`.

**Comment by shiehnpin** [comment]
In my opinion, aborting the connecting process in some stages might cause issues based on my previous experience. And most of them are coming with error code 133. I think to allow cancellation before handshaking initiated during the connecting process should be enough. What do you suggest?

**Comment by Ted-kim-dev** [comment]
I have the same problem.
