### ISSUE TITLE
Seemingly unintended change in the Licence header of BleManager

### ISSUE THREAD

**Issue by CapnOdin** [NordicSemiconductor/Android-BLE-Library#228]
I am not sure if you want to be informed of this but in commit [c59cd4a5769863aae6fe8a3de9f1136f720ff91e](https://github.com/NordicSemiconductor/Android-BLE-Library/commit/c59cd4a5769863aae6fe8a3de9f1136f720ff91e) `IMPLIED WARRANTIES` in the license of **BleManager.java** was changed to `thisIED WARRANTIES`

**Comment by CapnOdin** [comment]
In the **README.md** it says `Log.INDO` in the example extension of `BleManager` which I presume should have been `Log.INFO`

**Comment by philips77** [comment]
Thank you! I'll fix that. I love that your read licences in each file ;)
