### ISSUE TITLE
Multiple Connection

### ISSUE THREAD

**Issue by pritam2102** [NordicSemiconductor/Android-BLE-Library#233]
Can we connect multiple ble device using library and communication.

**Comment by philips77** [comment]
Hello,
Yes, you can. For each connected device you need to have separate instance of `BleManager`. We have an example of it in here: [Proximity profile in nRF Toolbox](https://github.com/NordicSemiconductor/Android-nRF-Toolbox/tree/master/app/src/main/java/no/nordicsemi/android/nrftoolbox/proximity). The service extends [BleMulticonnectProfileService](https://github.com/NordicSemiconductor/Android-nRF-Toolbox/tree/master/app/src/main/java/no/nordicsemi/android/nrftoolbox/profile/multiconnect) which keeps the list of all devices, for which connection was created.
If you're using also the GATT server, there should be one instance of the `BleServerManager` which you set to all `BleManager` objects using `useServer(...)`.

**Comment by pritam2102** [comment]
Thank You
