### ISSUE TITLE
PHY not supported

### ISSUE THREAD

**Issue by pritam2102** [NordicSemiconductor/Android-BLE-Library#236]
Got issue in only nokia 6.1 "PHY updated failed with status 6" how to resolve please help me.

**Comment by philips77** [comment]
Could you share your logs and describe what you are doing exactly? What is the version if Android on that phone? Can you also post a screenshot from nRF Connect -> Device Information screen taken on this phone?

**Comment by pritam2102** [comment]
Ble is connected but not getting a response from ble on mobile

Log:-   
Requesting preferred PHYs...
gatt.setPreferredPhy(LE 2M, LE 2M, coding option = No preferred)
PHY updated failed with status 6
Requested PHY not supported: 6
Connection parameters updated (interval: 45.0ms, latency: 0, timeout: 5000ms)

Device Info :- 
Device Name:- Nokia 6.1 
Version :- Android 10

![nrf issue](https://user-images.githubusercontent.com/38606313/91557326-ed3c5b80-e951-11ea-98f6-57f455e546d3.png)

**Comment by philips77** [comment]
Well.. looks like one of the devices: your phone or the peripheral does not support PHY LE 2M. It's not an issue, I would say.

**Comment by okbean** [comment]
see the constant GATT_REQUEST_NOT_SUPPORTED in class BluetoothGatt, the value is 0x6.
it means that，setPreferredPhy request is not support on nokia 6.1.

**Comment by habbasi-rsc** [comment]
@philips77 Should we check the Android version manually before using such this `.add(setPreferredPhy(PhyRequest.PHY_LE_2M_MASK, PhyRequest.PHY_LE_2M_MASK, PhyRequest.PHY_OPTION_NO_PREFERRED)`
?
Or the library does this internally?

**Comment by Drjacky** [comment]
@philips77 Should we check the Android version manually before using such this .add(setPreferredPhy(PhyRequest.PHY_LE_2M_MASK, PhyRequest.PHY_LE_2M_MASK, PhyRequest.PHY_OPTION_NO_PREFERRED)
?
Or the library does this internally?

**Comment by philips77** [comment]
The library should check it and also check if requested phy is supported.
