### ISSUE TITLE
Support for peripheral-only use-case

### ISSUE THREAD

**Issue by huntc** [NordicSemiconductor/Android-BLE-Library#237]
The new server implementation demands that a central device is connected to when the server is behaving as peripheral-only. Perhaps we can have a means of associating a BLE manager without requiring a connection e.g. require just a `useServer` without a `connect` to follow it.

**Comment by usikder** [comment]
I noticed the same thing in https://github.com/NordicSemiconductor/Android-BLE-Library/issues/229 and hope to address it in https://github.com/NordicSemiconductor/Android-BLE-Library/pull/231.

**Comment by huntc** [comment]
Ah, apologies for the duplication. Will close this one and track yours. Thanks.
