### ISSUE TITLE
Problem extending BleManagerGattCallback

### ISSUE THREAD

**Issue by cece95** [NordicSemiconductor/Android-BLE-Library#239]
Good morning, 
i just started working with BLE and i started by copying the example from the README. 

Specifically at a certain point you do

```java
       private class MyManagerGattCallback extends BleManagerGattCallback {

        // This method will be called when the device is connected and services are discovered.
        // You need to obtain references to the characteristics and descriptors that you will use.
        // Return true if all required services are found, false otherwise.
        @Override
        public boolean isRequiredServiceSupported(@NonNull final BluetoothGatt gatt) {
            final BluetoothGattService service = gatt.getService(SERVICE_UUID);
            if (service != null) {
                firstCharacteristic = service.getCharacteristic(FIRST_CHAR);
                secondCharacteristic = service.getCharacteristic(SECOND_CHAR);
            }
            [...]
        }
```

When i tried to replicate your code i got an error because the class `BleManagerGattCallback` is protected and thus i cannot extend it. Is it an expected behaviour? What should i do to make your example work again?

Thank you in advance

Best
Cesare

**Comment by philips77** [comment]
You need to extend it in your `BleManager` implementation. Take a look here: https://github.com/NordicSemiconductor/Android-nRF-Blinky/blob/2f3a06bf0e0c62a8172ac7fe2d872ac62ec19d84/app/src/main/java/no/nordicsemi/android/blinky/profile/BlinkyManager.java#L156

**Comment by cece95** [comment]
Oh ok thanks, problem solved!
