### ISSUE TITLE
How do I connect to my Ble device?

### ISSUE THREAD

**Issue by andrew203** [NordicSemiconductor/Android-BLE-Library#243]
When I finished the scan, I had the results. How do I connect to my Ble device?
```java
   BluetoothLeScannerCompat scanner = BluetoothLeScannerCompat.getScanner();
        ScanSettings settings = new ScanSettings.Builder()
                .setLegacy(false)
                .setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY)
                .setReportDelay(1000)
                .setUseHardwareBatchingIfSupported(false)
                .build();
        List<ScanFilter> filters = new ArrayList<>();
        //  filters.add(new ScanFilter.Builder().setServiceUuid(mUuid).build());
        scanCallback=new ScanCallback() {
            @Override
            public void onScanResult(int callbackType, @NonNull ScanResult result) {
                super.onScanResult(callbackType, result);
            }

            @Override
            public void onBatchScanResults(@NonNull List<ScanResult> results) {
                super.onBatchScanResults(results);
                for(int i=0;i<results.size();i++){
                    Log.e(TAG,"onBatchScanResults="+results.get(i).getDevice().getAddress());
                }
            }

            @Override
            public void onScanFailed(int errorCode) {
                super.onScanFailed(errorCode);
            }
        };
        scanner.startScan(filters, settings, scanCallback);
        scanning = true;
    }
```
![image](https://user-images.githubusercontent.com/8021798/93344971-e3c55580-f864-11ea-9494-cdb59b32b786.png)

**Comment by philips77** [comment]
Hi, have a look at our examples, e.g. here:
https://github.com/NordicSemiconductor/Android-nRF-Blinky/blob/2f3a06bf0e0c62a8172ac7fe2d872ac62ec19d84/app/src/main/java/no/nordicsemi/android/blinky/viewmodels/BlinkyViewModel.java#L66

**Comment by andrew203** [comment]
Thank you for your reply

**Comment by andrew203** [comment]
> Hi, have a look at our examples, e.g. here:
> https://github.com/NordicSemiconductor/Android-nRF-Blinky/blob/2f3a06bf0e0c62a8172ac7fe2d872ac62ec19d84/app/src/main/java/no/nordicsemi/android/blinky/viewmodels/BlinkyViewModel.java#L66

Thank you for your reply

**Comment by andrew203** [comment]
> https://github.com/NordicSemiconductor/Android-nRF-Blinky/blob/2f3a06bf0e0c62a8172ac7fe2d872ac62ec19d84/app/src/main/java/no/nordicsemi/android/blinky/viewmodels/BlinkyViewModel.java#L66

By the way，Besides the Blink project, what other examples can you refer to for connecting, sending and receiving data? I'm not familiar with LiveData

**Comment by philips77** [comment]
Check out the 2 latest Pull Requests.
