### ISSUE TITLE
BleManager   Question

### ISSUE THREAD

**Issue by andrew203** [NordicSemiconductor/Android-BLE-Library#244]
I've seen some demo and there are many different types of BleManager such as BatteryManager BlinkManager.

So I want to ask, if my app wants to connect to a BLE device and then do a transceiver with that device. How do I define it

**Comment by philips77** [comment]
You may find an example here:
https://github.com/NordicSemiconductor/Android-nRF-Blinky/blob/master/app/src/main/java/no/nordicsemi/android/blinky/profile/BlinkyManager.java

**Comment by andrew203** [comment]
> You may find an example here:
> https://github.com/NordicSemiconductor/Android-nRF-Blinky/blob/master/app/src/main/java/no/nordicsemi/android/blinky/profile/BlinkyManager.java

Can you set the length of the sending frame and the length of the receiving frame in this demo?

**Comment by philips77** [comment]
The length of a packet is defined by MTU (actually MTU- 3 bytes). The default MTU is 23, which gives 20 bytes of payload.
You may request longer by using
```java
requestMtu(...).enqueue();
```
When you write longer packets without response, or send them with notifications/indications from a server, you may use `split()` method, or a variant with parameters:
```java
writeCharacteristic(..., data)
   .split()
   .enqueue();
```

**Comment by andrew203** [comment]
> The length of a packet is defined by MTU (actually MTU- 3 bytes). The default MTU is 23, which gives 20 bytes of payload.
> You may request longer by using
> 
> ```java
> requestMtu(...).enqueue();
> ```
> 
> When you write longer packets without response, or send them with notifications/indications from a server, you may use `split()` method, or a variant with parameters:
> 
> ```java
> writeCharacteristic(..., data)
>    .split()
>    .enqueue();
> ```

Thank you for your reply
