### ISSUE TITLE
run failed

### ISSUE THREAD

**Issue by andrew203** [NordicSemiconductor/Android-BLE-Library#245]
```
Static interface methods are only supported starting with Android N (--min-api 24): float no.nordicsemi.android.ble.common.profile.bp.BloodPressureTypes.toKPa(float, int)

Default interface methods are only supported starting with Android N (--min-api 24): void no.nordicsemi.android.ble.common.profile.cgm.CGMSessionRunTimeCallback.onContinuousGlucoseMonitorSessionRunTimeReceivedWithCrcError(android.bluetooth.BluetoothDevice, no.nordicsemi.android.ble.data.Data)

Invoke-customs are only supported starting with Android O (--min-api 26)

Default interface methods are only supported starting with Android N (--min-api 24): void no.nordicsemi.android.ble.BleManagerCallbacks.onBatteryValueReceived(android.bluetooth.BluetoothDevice, int)
```

**Comment by philips77** [comment]
Did you set Java 8 features in your app, like described here:
https://developer.android.com/studio/write/java8-support

**Comment by andrew203** [comment]
> Did you set Java 8 features in your app, like described here:
> https://developer.android.com/studio/write/java8-support

![image](https://user-images.githubusercontent.com/8021798/93465026-c5229580-f91c-11ea-8c14-d2444ccb29d8.png)
I set in my project gradle

**Comment by andrew203** [comment]
> Did you set Java 8 features in your app, like described here:
> https://developer.android.com/studio/write/java8-support
Thank you for your reply and I have solved it
