### ISSUE TITLE
Cannot cancel connection with using autoConnect

### ISSUE THREAD

**Issue by VincentMasselis** [NordicSemiconductor/Android-BLE-Library#251]
I was connecting with `autoConnect` (but not yet connected) and, at some point, I decide to cancel the pending connection, the disconnection request is correctly enqueued but nothing appends, `internalDisconnect` is never called.

I'm using the last commit on develop (the one this morning), the cause of the bug seems to be the bool `operationInProgress` set to `true` here ->
https://github.com/NordicSemiconductor/Android-BLE-Library/blob/develop/ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java#L2828 causing the disconnection request to be enqueued and but never launched.

**Comment by philips77** [comment]
Yes... this use case may not be supported.

**Comment by VincentMasselis** [comment]
😢 Do you have any workaround that I could use for the moment ?

**Comment by philips77** [comment]
The initial connection, even with `autoConnect = true` is done with this param set to false (although see #250). It should timeout in 30 seconds, or when you set `.timeout(...)` parameter to the `ConnectRequest`. You may try calling `close()` and `connect(...).enqueue()` again, but I can't guarantee it will work as expected.

**Comment by VincentMasselis** [comment]
By `close()` you mean the one from `BleManager` or `BleManagerHandler` ?

**Comment by philips77** [comment]
True... How about using a different `BleManager` instance then?

**Comment by VincentMasselis** [comment]
Firstly, i'm injecting my manager instance at some places in my code, it's not gonna be easy to swap from one instance to another because of this ioc.
Secondly, forgetting my previous `BleManager` instance doesn't stops the running `autoConnect` connection, which leads, i thinks, to memories leaks.

**Comment by philips77** [comment]
You're right. Cancellation would really be a nice to have feature. I can look at it next week, but it's my last week before 3-month leave, so I can't promise much.

**Comment by VincentMasselis** [comment]
I'm sending all the virtual encouragements I could behind my computer 💪

**Comment by philips77** [comment]
I've started working on this feature now.
