### ISSUE TITLE
Crash in enqueue()

### ISSUE THREAD

**Issue by spicarle** [NordicSemiconductor/Android-BLE-Library#252]
This happens once a week, when I restart my app (first time after restart) I connect an already paired device and try to setIndicate...

If i understand well the queue could be null after a discover service... 

I don't have more information, only my firebase craches :

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'boolean java.util.Deque.add(java.lang.Object)' on a null object reference

no.nordicsemi.android.ble.BleManagerHandler.enqueue (BleManagerHandler.java:1228)
no.nordicsemi.android.ble.Request.enqueue (Request.java:1179)
com.biocorp.mallya.ble.peripheral.NordicBleWrapper$NordicBleManager.setIndicate (NordicBleWrapper.kt:345)
com.biocorp.mallya.ble.peripheral.NordicBleWrapper.setNotifying (NordicBleWrapper.kt:127)
```

**Comment by philips77** [comment]
Hi,
First of all, sorry for the very late response. I finally have time to come back to the BLE lib.

I found the possible root cause of why you'd end up with this crash.
