### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by 979451341** [NordicSemiconductor/Android-BLE-Library#263]
```
no.nordicsemi.android.ble.BleManager$BleManagerGattCallback.lambda$nextRequest$3$BleManager$BleManagerGattCallback(BleManager.java:3408)
```
```
no.nordicsemi.android:ble:2.1.1
```

**Comment by roshanrajaratnam** [comment]
Hi could you post some more information with logs please?

**Comment by 979451341** [comment]
> Hi could you post some more information with logs please?


1 no.nordicsemi.android.ble.BleManager$BleManagerGattCallback.lambda$nextRequest$3$BleManager$BleManagerGattCallback(BleManager.java:3408)
--
2 no.nordicsemi.android.ble.-$$Lambda$BleManager$BleManagerGattCallback$lHohduzEoh65ydpbEB2__CX1LGU.run(Unknown Source:4)
3 android.os.Handler.handleCallback(Handler.java:883)
4 android.os.Handler.dispatchMessage(Handler.java:100)
5 android.os.Looper.loop(Looper.java:224)
6 android.app.ActivityThread.main(ActivityThread.java:7584)
7 java.lang.reflect.Method.invoke(Native Method)
8 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
9 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by philips77** [comment]
This could have been fixed in the latest releases. Please migrate to 2.2.4.
I'll be releasing 2.3 in few days with better Kotlin support.
