### ISSUE TITLE
Connection failed, status: 133, -4, -5, -7

### ISSUE THREAD

**Issue by wanglei0309** [NordicSemiconductor/Android-BLE-Library#264]
The connection fails all the time on the Huawei mata 10 mobile phone, and the return status code is shown in the title. I carefully read the 133 related issues post, but did not find a solution. please help me. Thank you

**Comment by zetokz** [comment]
@wanglei0309, unfortunately, the error 133 during connection is happening very often regardless of the library used for BLE even using native android Bluetooth stack you will see such error same frequently. As well as this error does not have one clear reason of occurrence. The only way to deal with it is to try one more time.
