### ISSUE TITLE
Can i do Auto bonding...

### ISSUE THREAD

**Issue by pritam2102** [NordicSemiconductor/Android-BLE-Library#265]
Hello,
I am using latest version 2.2.4. in that can I do auto bonding without doing manual pairing. And is this possible to do bonding before connecting.

**Comment by philips77** [comment]
You may use standard Android API for bonding before connecting. Call `createBond()` on `BluetoothDevice` object. If no additional data are required, like PIN or passphrase, this may be transparent to the user. On some phones a popup may show up.
