### ISSUE TITLE
Does not receive data after the device was connected

### ISSUE THREAD

**Issue by Stalker11** [NordicSemiconductor/Android-BLE-Library#266]
Hello
I have some issues. Method on `onDataReceived` does not call after the device was connected (method `onDeviceConnected` was called). But for another device, it works fine.
These issues reproduce on v2.2.4. Library version 1.2.0 works fine.
What does it depend on?
Could you help me solve this problem?
Code:
![initialize](https://user-images.githubusercontent.com/15062516/102603535-9db1b380-412b-11eb-9ebd-b0c60d14dc20.JPG)

**Comment by zetokz** [comment]
@Stalker11 could you, please, attach some logs from your device to the issue?
It is almost impossible to say what is wrong, from a code perspective at least what is visible here everything is fine =)

**Comment by philips77** [comment]
Hello @Stalker11,
Did you manage to solve the issue? Sorry for coming back to you so late, I was busy with other tasks.

From the top of my mind, the callback may not getting called for the following reasons:
1. your characteristics are *null*
2. they don't have READ property

In both cases you should get `fail` callback instead.

**Comment by philips77** [comment]
Closed due to inactivity.
