### ISSUE TITLE
Bintray is shutting down

### ISSUE THREAD

**Issue by SarthakJ10** [NordicSemiconductor/Android-BLE-Library#281]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
Bintray is shutting down and from the gradle it looks like the library uses Bintray to publish. Bintray will be shutdown in 3 months.

**Comment by philips77** [comment]
The lib is already available on Maven Central. I'm working now on migrating publish scripts to publish on Maven only, without first using Bintray.
