### ISSUE TITLE
[Question] Custom OOB bonding

### ISSUE THREAD

**Issue by Chevalier-Maxime** [NordicSemiconductor/Android-BLE-Library#282]
Hi everyone,
I'm new to the library and can't figure out how I could bond after the connexion to a device. I saw a post on the devzone explaining that the bond should be performed in the initialize() method. But I would like to perform a "custom" bond (OOB) using reflection (on a custom OS).

Is it possible to do this using the library (as it seems that I should override/add a createBond method in BleManagerHandler) through some custom request ? Or should I manage this manually and then use the library ?

**Comment by philips77** [comment]
Hello,
It is the OS that handles bonding. The library just calls `BluetoothDevice.createBond()` and that's the only API available. If you're working on a custom OS based on AOSP, you should create the bond manually and then, if needed, use this lib for connection.
