### ISSUE TITLE
createBond returning twice

### ISSUE THREAD

**Issue by Rawa** [NordicSemiconductor/Android-BLE-Library#30]
Hello,

I'm using we are using your library for managing my BT connections and mostly it is working great. But I seem to run into some problems with the bonding process. It seems like the enqueue gets two callbacks, done and fail. 

In short what happens is, I connect, create a bond, get success (done). I then disconnect and remove the bond and receive a fail.

I added a random number to log to just clarify I'm not calling the function twice.

```
D/RxBt: createBond 0.6858416588166597
I/BluetoothDevice: createBond() for device 91:3 called by pid: 623 tid: 623
E/RxBt: Bonding required
E/RxBt: Bonded!
D/RxBt: Already Bond success 0.6858416588166597
D/BluetoothDevice: bond, retrieved method: public boolean android.bluetooth.BluetoothDevice.removeBond()
I/BluetoothDevice: removeBond() for device 91:3 called by pid: 623 tid: 623
D/RxBt: Already Bond Fail 0.6858416588166597
```

**Comment by Rawa** [comment]
I can try and produce a minimal reproducible example if needed.

**Comment by philips77** [comment]
Hi, could you try the version from branch *bugfix/29*? You need to add the library as module, not from jcenter"

In **build.gradle**:
```groovy
    // api 'no.nordicsemi.android:ble:2.0-beta4'
    api project(":ble")
```
In **settings.gradle**:
```groovy
include ':ble'
project(':ble').projectDir = file('../Android-BLE-Library/ble')
```
*../Android-BLE-Library/ble* is the path to *ble* module.

**Comment by philips77** [comment]
Btw, thanks for testing the library!
