### ISSUE TITLE
[QUESTION] Which library do you guys use for BLE communication in iOS?

### ISSUE THREAD

**Issue by luk3skyw4lker** [NordicSemiconductor/Android-BLE-Library#300]
Hi, I'm developing a cross-platform app to work with BLE communication and found your app and tested it, the comunication was pretty fast and reliable, so I came to Github and found the BLE library for Android (I suppose this is the one) but for some reason I didn't found the iOS one, so I thought that maybe asking here would be a good idea.

Anyway, I am sorry for any troubling or pollution and I am already thanking you guys for the attention :)

**Comment by philips77** [comment]
Hello,
On the iOS side we use the native API directly. Its design is much better and there are no weird errors that happen on Android. Of course it could be wrapped in a library with similar API, but we simply didn't have time to do it.
