### ISSUE TITLE
BleManagerGattCallback becomes abstract class?

### ISSUE THREAD

**Issue by Simonida** [NordicSemiconductor/Android-BLE-Library#307]
Migrating from the version 2.2.4 to the version 2.3.0 is breaking the current implementation.
I have a class that is called BleGattCallback, which extends the BleManagerGattCallback, and was getting the GattCallback instance like this:
```
override fun getGattCallback(): BleManagerGattCallback {
         return BleGattCallback()
}
```

But in the new version, the following error is happening:
_Class 'BleGattCallback' is not abstract and does not implement abstract base class member protected/*protected and package*/ abstract fun onServicesInvalidated(): Unit defined in no.nordicsemi.android.ble.BleManager.BleManagerGattCallback_

How to instantiate GattCallback now?

The referent project Android-nRF-Blinky is using the old library version.

**Comment by philips77** [comment]
Oh, yes. Sorry for not mentioning this new method in the migration guidelines. Previous name was misleading as this may happen not only when the device is disconnected.
