### ISSUE TITLE
Kotlin cannot access package-private

### ISSUE THREAD

**Issue by ddB0515** [NordicSemiconductor/Android-BLE-Library#309]
Hi

As I have started using library having issue with access to ObservableBleManager and getting this error, not sure what is causing it...
Anyone had same issue and how to resolve it???

Cannot access 'ObservableBleManager': it is package-private in 'no.nordicsemi.android.ble.livedata'
![image](https://user-images.githubusercontent.com/20762436/127523666-4b92a03b-2479-4d56-9eec-02b8c15d4145.png)

Using Kotlin 1.5.21 (if is needed) and using via maven (not as module)

Edit: Tried with 2.2.4 and works normally :thinking:

**Comment by philips77** [comment]
Yes, we found it as well. I'll fix it when I can. Sorry for that. For now you may copy the class to your project.

**Comment by philips77** [comment]
This has now been fixed and will be released as 2.3.1.
