### ISSUE TITLE
Disconnect  immediately after the connect the Bluetooth

### ISSUE THREAD

**Issue by tigerjiang** [NordicSemiconductor/Android-BLE-Library#310]
When  I running the newest code with **Android-nRF-Toolbox** ,The app exit and got the below log. 
![WechatIMG147](https://user-images.githubusercontent.com/3772302/127591757-be3b2bb8-7fc2-4cb4-b54b-02628228e7cb.jpeg)

<img width="768" alt="WechatIMG246" src="https://user-images.githubusercontent.com/3772302/127591907-c8ed26fb-d36a-4de5-bc8d-4338f46e9810.png">

**Comment by philips77** [comment]
Looks like you're running the wear module, designed for watches. Change to app next to the Run button in Android Studio.
