### ISSUE TITLE
Add option to get split write progress and merge progress as Flow

### ISSUE THREAD

**Issue by uberchilly** [NordicSemiconductor/Android-BLE-Library#315]
Is there a way to receive progress of sending message that needs to be split into smaller ones, but also use ```suspend()``` extension for coroutine support?

**Comment by philips77** [comment]
Hmm.. I didn't think of it. We could add a way to get flow with progress updates. I'll look into it in the next release.

**Comment by philips77** [comment]
I've started working on this feature.

**Comment by philips77** [comment]
Hello, we've just added #371. If you could check if it makes sense, is readable, and works, that would be amazing. Otherwise, I think I'll merge it and will let the time validate it :)
