### ISSUE TITLE
ConnectionPriorityRequest support question

### ISSUE THREAD

**Issue by SarthakJ10** [NordicSemiconductor/Android-BLE-Library#326]
Hi!
Firstly, what is the best practice on requesting a ConnectionPriorityRequest during a connection to the BLE Peripheral?
When should that be requested? Is it before sending the `connect` command or before bonding to the peripheral?

Secondly, can you change the connection priority after you have already connected to the peripheral? For eg: A BLE peripheral is already connected to the central, but now we would like to make the connection high priority and low latency before starting a firmware update. How would one achieve that? Should I just call the method 
``` kotlin
requestConnectionPriority(ConnectionPriorityRequest.CONNECTION_PRIORITY_HIGH)
```
And then if the callback succeeds, start a FW Update? Are there any delays that I should be aware of on getting any callbacks?

**Comment by philips77** [comment]
Hello,

Sorry for the late reply.

> When should that be requested? Is it before sending the connect command or before bonding to the peripheral?

You may call this method any time after you've connected to the device. All it does it requests one of 3 preconfigured connection parameters, so specifies how fast packets are to be sent from now on, how many of them can be ignored and when the host should disconnect it the peripheral doesn't respond. Mind, that all 3 options (priorities) use Supervision Timeout set to 20 seconds for some unknown reason, at least on older Android versions. I didn't check recently. Supervision Timeout specifies the time after which the host (Android in this case) will receive disconnection event after three link was lost (e.g. you reset the device). Connection Parameters can also be requested from there peripheral side, and there you can set any[^1] values.

BLE library will receive a callback (callback for that method was added around Android 8ish), and will emulate a delay for older versions. You should assume that when the request is done, the required callback was obtained.

[^1]: Minimum connection interval supported by Android is 11.25 ms.

**Comment by philips77** [comment]
Have a look at 7e3b4f5c5505f151f358989034328159e5a9b62f.
In Android 8 default supervision timeout has been lowered to 5 seconds.
