### ISSUE TITLE
How to get instance of customBleManager from System UI connected device

### ISSUE THREAD

**Issue by trix0** [NordicSemiconductor/Android-BLE-Library#327]
Hi, I have a question.

If i connect device using system ui(Going to the bluetooth settings and connecting to the device)

Is there a way how can i retrieve my CustomBleManager out of that connection?

Do we have an  example of that ?

Thanks

**Comment by philips77** [comment]
You may get connected devices from`BluetoothManager`. You may also [open](https://github.com/NordicSemiconductor/Android-BLE-Library/blob/122319c029746f86e210874da642d5477b003817/ble/src/main/java/no/nordicsemi/android/ble/BleServerManager.java#L74) the GATT server and you'll immediately get [`onDeviceConnectedToServer`](https://github.com/NordicSemiconductor/Android-BLE-Library/blob/122319c029746f86e210874da642d5477b003817/ble/src/main/java/no/nordicsemi/android/ble/observer/ServerObserver.java#L21) with all devices connected to your Android device. From that method you may create BleManager instance and connect to it as client.

**Comment by trix0** [comment]
@philips77  Thanks @philips77 , I am able to get currently connected BluetoothDevice out of BluetoothManager.
However How do i get BleManagerGattCallback or (BluetoothGatt) without disconnecting and reconnecting.

**Comment by philips77** [comment]
Hello,

Sorry for super long delay. I hope you have solved your issue.
You may simply connect to the `BluetoothDevice` using your custom `BleManager`. The device may already be connected to the phone, it does not matter. Each client (`BluetoothGatt`) is a virtual connection and will be notified as if it was a single one, so you may connect it, disconnect, etc, without affecting any other. The physical connection will terminate when the last virtual connection client will disconnect.
