### ISSUE TITLE
how to support byte order in Data & MutableData

### ISSUE THREAD

**Issue by kkkbird** [NordicSemiconductor/Android-BLE-Library#328]
currently Data/MutableData only support get and set values in little endian. how to manipulate data in big endian order.
can we add a member function like ByteBuffer.order(ByteOrder bo) to support byte order switching endianess.

**Comment by philips77** [comment]
True, that's room for improvement. I'll mark it as feature request.

**Comment by philips77** [comment]
Merged. Will be released as 2.4. soon.
