### ISSUE TITLE
How to cancel Pair Device dialog

### ISSUE THREAD

**Issue by jswn0203** [NordicSemiconductor/Android-BLE-Library#329]
After using this library, the pairing box will automatically pop up every time the connection is not paired. How can I prevent it from popping up

**Comment by philips77** [comment]
I don't think you can. If the device requires pairing, depending on the method a pairing dialog may appear. Even if you provide the PIN in the app and actually the pairing may succeed (I don't remember if I ever managed to do so), the pairing dialog remains visible, making the whole `setPin` method weird from user perspective. For *just works* pairing method there will be no dialog, but also less security.
