### ISSUE TITLE
Connecting 2nd device receives failed 

### ISSUE THREAD

**Issue by Billideveloper** [NordicSemiconductor/Android-BLE-Library#341]
when connecting multiple devices the first device connects easily and when a 2nd device connection is established ble_manager return failed it even does not give any type of failed staus bug, I'm stuck here can someone help me with multiple device connections Already looked at the Toolbox proximity profile for multiple connections and it returns failed.

**Comment by philips77** [comment]
What phone are you using?
Phones should support multiple connections. Could you paste logs that you get from the 2nd connection?

**Comment by philips77** [comment]
I'm closing the issue due to inactivity. Should you still experience similar behaviour, please create a new issue.
