### ISSUE TITLE
You already know the Mac. According to the direct connection of the Mac, what will happen without scanning?

### ISSUE THREAD

**Issue by zhangwenxiang26** [NordicSemiconductor/Android-BLE-Library#342]

**Comment by philips77** [comment]
Without scanning, Android assumes public address type and will try to connect with the type flag set to public. If your device has a random address, connection will timeout. 
The type, public or random, is 49th bit of the Mac address, which cannot be set with Android API. Android stores the type in some internal database when scans a device and uses this cache when connecting.

**Comment by philips77** [comment]
Have a look at https://www.novelbits.io/bluetooth-low-energy-advertisements-part-1/ and the `TxAdd` flag. This is the 49th bit of the address.
