### ISSUE TITLE
Memory allocation due to logging

### ISSUE THREAD

**Issue by x2764tech** [NordicSemiconductor/Android-BLE-Library#346]
I'm streaming packets from a device that sends a lot of data via notifications.

During memory profiling, I'm seeing that [`BleManagerHandler.gattCallback.onCharacteristicChanged`][1] allocates several strings for each packet. These seem to be soley for the purpose of logging (which my implementation then ignores)

Would it be possible for the library to check whether `INFO` logging is enabled *before* calling `ParserUtils.parse` and `log(level.Debug, ...)`, and thereby avoid these unnecessary string allocations?

[1]: https://github.com/NordicSemiconductor/Android-BLE-Library/blob/6d3c95f2fdb75485cdcb489e19b912e9173660a1/ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java#L2287

**Comment by philips77** [comment]
Yes, we observed it as well. I'll add option to disable logs, one optimize them in the next version.

**Comment by x2764tech** [comment]
@philips77 Amazing. Thank you 🙏 
Do you have any idea of when the next release might be? More for managing expectations than anything else.

**Comment by philips77** [comment]
I already implemented changes and doing some testing. I'll push the changes today and create a PR for review.

**Comment by philips77** [comment]
Ok, that "today" became a week. I promise never to promise anything more!
But have a look at the PR and check if you need anything more.
