### ISSUE TITLE
Co-existence of multiple managers & state sharing

### ISSUE THREAD

**Issue by marianhlavac** [NordicSemiconductor/Android-BLE-Library#361]
From README we know that having multiple managers is allowed. When having multiple managers for a single device, is it possible for the managers to share the connection state (or better re-using the same state machine for all managers)?

I'd refrain from having multiple managers for a single device, but we're using the [Android-nRF-Connect-Device-Manager](https://github.com/NordicSemiconductor/Android-nRF-Connect-Device-Manager) library in our project, and we'd like to combine the SMP communication with custom communication on our own characteristics. The docstring for McuMgrBleTransport [mentions that other BLE communication can be done](https://github.com/NordicSemiconductor/Android-nRF-Connect-Device-Manager/blob/463dc46aac2310f40bc275fa2c309eda630085d4/mcumgr-ble/src/main/java/io/runtime/mcumgr/ble/McuMgrBleTransport.java#L61) using _enqueue_ (which is already deprecated btw), but it seems that doesn't count with communication on other characteristics.

I've considered following approaches so far:

1. (our current approach) Having separate managers for SMP communication and our own communication. _The manager states are not in sync (one is connected, second might be not) -> state duplication_
2. (our previous approach) Rewriting the McuMgrBleTransport from device manager library, with overriden getGattCallback(), which includes our characteristics in `isRequiredServiceSupported`. _This doesn't scale and leads to unnecessary duplication of the code from the device manager library_ (McuMgrGattCallback is private and is accessing private members of McuMgrBleTransport) _-> code duplication_

Both approaches are insufficient, I'd like to find a solution that prevents code and state duplication.

**Is there any way to "extend" an existing manager to get more services and characteristics to work within a single manager?**

Is the `isRequiredServiceSupported` method the only place in the code to work with BluetoothGatt instance? I am aware of the [connectGatt](https://developer.android.com/reference/android/bluetooth/BluetoothDevice#connectGatt(android.content.Context,%20boolean,%20android.bluetooth.BluetoothGattCallback)) method, but unsure how to use it to not disrupt the functioning of BLEManager.

**Comment by philips77** [comment]
> When having multiple managers for a single device, is it possible for the managers to share the connection state (or better re-using the same state machine for all managers)?

No, each manager is associated with a different `BluetoothGatt` object, which is a client object. Disconnecting from one does not mean disconnecting from other.

> ...using enqueue (which is already deprecated btw)

Thanks, will fix that.

> Is there any way to "extend" an existing manager to get more services and characteristics to work within a single manager?

OK, that looks like a feature request for nRF Connect Device Manager library. I'll add it to our backlog. As I understood, you'd like to be able to extend `McuMgrBleTransport` and get access to other services to be able to use them in your app. That's doable, but the change will appear in nRFCDM lib, not here.

**Comment by philips77** [comment]
Have a look at https://github.com/NordicSemiconductor/Android-nRF-Connect-Device-Manager/pull/44. Would be great to get some feedback from you tomorrow.
