### ISSUE TITLE
Kotlin: confusing and undocumented BleManager.stateAsFlow behaviour

### ISSUE THREAD

**Issue by DavidJRobertson** [NordicSemiconductor/Android-BLE-Library#364]
I had assumed that calling BleManager.stateAsFlow() multiple times would return the same flow, but it does not. Further, calling it actually breaks previously-returned flows as it overwrites the connection observer that is used to update the flow. 

Ideally, the same flow should be returned. This could be accomplished by storing the MutableStateFlow instance on the ConnectionObserver subclass, and then only replacing the ConnectionObserver if it is not the right type. In fact, arguably it would be a confusing side effect for any existing ConnectionObserver to be replaced when calling this method - suggest throwing an exception if there is already one registered.

**Comment by philips77** [comment]
On it. Thank you for reporting it.

**Comment by philips77** [comment]
Hi, could you please review the PR?

**Comment by philips77** [comment]
Released in 2.4.0-beta03. Please test if it works for you. We're getting ready to release 2.4.0 final next week.
