### ISSUE TITLE
Does this support multiple peripherals?

### ISSUE THREAD

**Issue by williamtan37** [NordicSemiconductor/Android-BLE-Library#369]
Hi, 

I read the documentation and it says the service supports multiple connections. Does this mean it supports multiple peripherals? Would appreciate a confirmation.

Thanks!

**Comment by philips77** [comment]
Yes. A `BleManager` instance can be used to connect to a single device, but you may have multiple instances of the manager, each for a different device. Phone should support at least 6 simultaneous connections, but keep in mind, that all connections share the same controller, so packets are sent in serial, not parallel.

Also. if needed, more than one manager instance can be used to connect to the same device, e.g. to separate some functionality. But then all of the managers keep separate connection state, and i.e. all need to be disconnected for the device to disconnect.

**Comment by philips77** [comment]
Related: #361
