### ISSUE TITLE
Delay coming before service discovery

### ISSUE THREAD

**Issue by mrdesai109** [NordicSemiconductor/Android-BLE-Library#380]
**After successful connection with BLE device there is a wait of 300 ms to discover the services.**

**How we can reduce/disable this wait time?**

Find the logs below.

2022-04-22 16:09:14.481 BleLog: Connected to 00:AA:11:BB:CC:DD
2022-04-22 16:09:14.481 BleLog: **wait(300)**
2022-04-22 16:09:14.782 BleLog: Discovering services...

**Comment by philips77** [comment]
Use
https://github.com/NordicSemiconductor/Android-BLE-Library/blob/42128bf3b0c6b571404992c81df44c21f33f89d2/ble/src/main/java/no/nordicsemi/android/ble/BleManager.java#L516-L519
