### ISSUE TITLE
Add a read callback for server characteristics 

### ISSUE THREAD

**Issue by sam131208** [NordicSemiconductor/Android-BLE-Library#385]
Hi:
   How to set current time service with GATT server?
   When I use setCharacteristicValue to periodically set the time, I can't get a more precise time.

Thanks!
 Sam

**Comment by philips77** [comment]
Interesting case. I'll add a task to add a read callback. Don't know yet if it will be easy.

**Comment by philips77** [comment]
This is related to #381.
