### ISSUE TITLE
Requested mtu like 500 bytes, but on the device side I received only 497

### ISSUE THREAD

**Issue by georrge1994** [NordicSemiconductor/Android-BLE-Library#393]
Hi, Nordic Semiconductor team. I faced with some problem, but not sure... When I tried to request MTU every time I got MTU - 3. I think lib use 3 bytes for self, can you explain me for clear work? Thank you very much!

**Comment by philips77** [comment]
Have a look at the doc in the code: 
https://github.com/NordicSemiconductor/Android-BLE-Library/blob/0c25823307d9b9401ab405d620777fc36a6dd259/ble/src/main/java/no/nordicsemi/android/ble/BleManager.java#L1827-L1842
