### ISSUE TITLE
After disabling phone's bluetooth BleManager.isReady returns true

### ISSUE THREAD

**Issue by darek607** [NordicSemiconductor/Android-BLE-Library#398]
After disabling bluetooth on the phone, the `BleManager.isReady` of my connected peripheral still returns true (I tested at least 2 minutes after disabling BT), however the `isConnected` correctly returns false. Also the `DISCONNECTED` event is correctly fired in the connection observer.

I'm using `isReady` to check if a user can interact with peripheral (e.g. after button click in the app). As a workaround I use `isReady && isConnected` to be sure the device is ready to work, however I would expect that if `isConnected` is false, the `isReady` also is false.

Library version: 2.4.1
Devices: Pixel 5 (Android 12), Samsung Galaxy A21S (Android 11)

Thanks for awesome library!

**Comment by philips77** [comment]
Thanks for the awesome bug report!

We'll look into it shortly.
