### ISSUE TITLE
Integrate with the Bond Management Service

### ISSUE THREAD

**Issue by eliotstock** [NordicSemiconductor/Android-BLE-Library#4]
Great to see all this code in a separate repo! I'll be migrating to it ASAP.

One feature request though: it would be great to see some integration with the bond management service so that I can request the deletion of the current bond with deleteBond() or some such method.

**Comment by philips77** [comment]
Thanks for the suggestion. I'll look into it.
Right now I'm working on improving sending/receiving long data (automatic splitting) and adding per-request callbacks.

**Comment by philips77** [comment]
Hi, please check out the develop branch. Also, there is BLE Common Library (also under development, develop branch) where i could add Bond Management Service.

**Comment by philips77** [comment]
HI @eliotstock, could you give some more input on this task?

**Comment by eliotstock** [comment]
Afraid I haven't been able to integrate with the develop branch yet - we need something pretty stable for now. I'll update this issue if I can find the time. Feel free to close it in the meantime if you like.

**Comment by eliotstock** [comment]
Closing this for now, since it looks like there's nothing special about the bond management service that would make sense to integrate in the BLE library. I'll reopen if I hit any issues when using the service as I would any other service.
