### ISSUE TITLE
How to know interval connection of device ?

### ISSUE THREAD

**Issue by MaximeFootbar** [NordicSemiconductor/Android-BLE-Library#404]
Hello,

I'm working on a device and an application who use this library (2.1.1 version). I'm trying to recover interval connection parameter but I didn't find how.
With the nrf connect application I can have this information that why I'm asking if a solution is possible and if yes how ?

**Comment by philips77** [comment]
Hello,
Sorry for a late response. Have a look at #390. On Android Oreo or newer It is now (since version 2.5) possible to add a listener for the connection interval and other parameters. It is not possible to get it on previous versions unless you get this information from the device in some way.
