### ISSUE TITLE
Example with asFlow()?

### ISSUE THREAD

**Issue by AndreKR** [NordicSemiconductor/Android-BLE-Library#407]
Starting from the example code in the readme I am able to get notifications by changing the `initialize()` method to
```kotlin
        override fun initialize() {
            requestMtu(517).enqueue()

            setNotificationCallback(realTimeDataC).with { device, data ->
                Log.i("CT", "Notification received")
            }
            enableNotifications(realTimeDataC).enqueue()
        }
```

It is unclear to me how I can get a flow with these notifications.

I tried adding a method like this to MyBleManager:
```kotlin
    fun realTimeDataFlow(): Flow<Data> {
        val flow = setNotificationCallback(realTimeDataC).asFlow()
        enableNotifications(realTimeDataC).enqueue()
        return flow;
    }
```

This didn't work, nothing is collected on the flow. I suspect this is maybe because the method is called _before_ initialize?

If that is in fact the reason, then I don't see how I could make it work. The flow is needed when the activity starts and `initialize()` is only called some time later.

I also tried leaving `enableNotifications(realTimeDataC).enqueue()` in `initialize()` but that didn't help either.

**Comment by AndreKR** [comment]
As a workaround, I'm sending the data through a channel now:
```kotlin
        override fun initialize() {
            requestMtu(517).enqueue()

            setNotificationCallback(realTimeDataC).with { device, data ->
                realTimeDataChannel.trySend(data)
            }
            enableNotifications(realTimeDataC).enqueue()
        }
```

**Comment by philips77** [comment]
Have a look at nRF Toolbox, for example here:
https://github.com/NordicSemiconductor/Android-nRF-Toolbox/blob/100a98d0328177aa7138a0c8d065b11b2ea6ba1f/profile_csc/src/main/java/no/nordicsemi/android/csc/data/CSCManager.kt#L94-L126

**Comment by philips77** [comment]
Indeed, your `realTimeDataFlow()` must be called when the device is ready (initialize complete) or in `initialize`. Before that, the characteristic references are null.
