### ISSUE TITLE
Publicly available javadoc

### ISSUE THREAD

**Issue by schattennarr** [NordicSemiconductor/Android-BLE-Library#408]
Hi,

I feel kinda stupid to ask this, but is there a javadoc available (I mean inline documentation exists) and if so, could it maybe linked into the readme?
Or do I have to compile it myself?

**Comment by philips77** [comment]
Hi,
There is no public javadoc available. We only have the online doc and example on GitHub and some sample apps. But we can gladly help, if you need anything. Any problems so far?

**Comment by schattennarr** [comment]
Nah, everything is working like a charm so far. I'll ask if I bump into any issue. :)
