### ISSUE TITLE
example for splitWithProgressFlow()？

### ISSUE THREAD

**Issue by almosting** [NordicSemiconductor/Android-BLE-Library#409]

**Comment by corentin-c** [comment]
Providing a description would be nice, with what you want to do with it for example
Something like this should work

`
    suspend fun writeCharacteristicWithProgression(
        characteristic: BluetoothGattCharacteristic,
        data: ByteArray,
        writeType: Int,
        splitter: DataSplitter
    ): Flow<ProgressIndication> {
        return withContext(Dispatchers.IO) {
            val writeRequest = super.writeCharacteristic(characteristic, data, writeType)
            val flow = writeRequest.splitWithProgressFlow(splitter)
            writeRequest.enqueue()
            flow
        }
    }
`

**Comment by philips77** [comment]
Thank you @corentin-c !

**Comment by almosting** [comment]
Thank you @corentin-c
