### ISSUE TITLE
disconnect the device

### ISSUE THREAD

**Issue by Kevin-Leung** [NordicSemiconductor/Android-BLE-Library#411]
hi, can u explain to disconnect a connected device, 
I'm trying to use disconnect() in 
```java
public final DisconnectRequest disconnect() {
   return Request.disconnect().setRequestHandler(requestHandler);
}
```
but nothing happend,

**Comment by niklasdahlheimer** [comment]
In your class which extends BleManager you can call

```java
disconnect().enqueue();
```

which triggers an async disconnect. you can add callbacks when disconnect succeeds or fails by calling

```java
  disconnect()
                .done(this::onDisconnected)
                .fail(this::onConnectionOperationFailed)
                .enqueue();
```
where onDisconnected and onConnectionOperationFailed are functions in your class which have a signature like
```kava
protected void onDisconnected(BluetoothDevice device){
// your callback code
}
```

**Comment by philips77** [comment]
Thank you @niklasdahlheimer for excellent answer!
