### ISSUE TITLE
writeCharacteristic is to slow

### ISSUE THREAD

**Issue by Kevin-Leung** [NordicSemiconductor/Android-BLE-Library#412]
hi,I am using writeCharacteristic to write a value to my BLE device(a light)
but  when I try to control the light with high frequency, the light cannot catch up with my speed, I mean, not smooth,
do u have any idea about this function?

**Comment by philips77** [comment]
Hi,
The write speed depends on many parameters:
1. Connection interval
2. Slave latency
3. Write type (write without response is faster)
4. Radio link quality (with lots of noise there can be a need for repetitions, etc.)
5. Length of the payload being sent

Please, work on those parameters to make it faster.
