### ISSUE TITLE
API 33 deprecated methods

### ISSUE THREAD

**Issue by sara-race-neato** [NordicSemiconductor/Android-BLE-Library#419]
There are a few methods that were deprecated in API 33 that I see are still used in this library:

- [BluetoothGatt.writeCharacteristic](https://developer.android.com/reference/android/bluetooth/BluetoothGatt?hl=en#writeCharacteristic(android.bluetooth.BluetoothGattCharacteristic))
- [BluetoothGatt.writeDescriptor](https://developer.android.com/reference/android/bluetooth/BluetoothGatt?hl=en#writeDescriptor(android.bluetooth.BluetoothGattDescriptor))
- [BluetoothGattCharacteristic.getValue](https://developer.android.com/reference/android/bluetooth/BluetoothGattCharacteristic?hl=en#getValue())
- [BluetoothGattCharacteristic.setValue](https://developer.android.com/reference/android/bluetooth/BluetoothGattCharacteristic?hl=en#setValue(java.lang.String))
- [BluetoothGattDescriptor.getValue](https://developer.android.com/reference/android/bluetooth/BluetoothGattDescriptor?hl=en#getValue())
- [BluetoothGattDescriptor.setValue](https://developer.android.com/reference/android/bluetooth/BluetoothGattDescriptor?hl=en#setValue(byte[]))

Is there a plan to replace these deprecated methods so that apps using this library can target API 33?

**Comment by philips77** [comment]
Yes, there is a plan :)
Thank you for the reminder.

Also, if you want, you could create a PR, that would speed things up!
