### ISSUE TITLE
Multiple Bluetooth connections will automatically disconnect after successful connection

### ISSUE THREAD

**Issue by 123yangu** [NordicSemiconductor/Android-BLE-Library#421]
Multiple Bluetooth connections will automatically disconnect after successful connection（HUAWEI P30）

**Comment by philips77** [comment]
Sorry, but I don't understand your question.

**Comment by 123yangu** [comment]
Generally, the maximum number of Bluetooth connections for Android devices is 7. However, when I connect 6 devices at the same time, I will automatically disconnect Bluetooth after successful connection

**Comment by 123yangu** [comment]
The current processing method is to make the next connection after a successful/failed connection. There is no problem for the time being, but there is a problem. The connection efficiency is too low

**Comment by 123yangu** [comment]
> Sorry, but I don't understand your question.

Generally, the maximum number of Bluetooth connections for Android devices is 7. However, when I connect 6 devices at the same time, a Bluetooth device will automatically disconnect after successful connection

**Comment by liujoshua** [comment]
P30 might be limited to 6. Number of concurrent connections is dependent on device hardware and installed OS
