### ISSUE TITLE
Device connected but not ready

### ISSUE THREAD

**Issue by talfsaverone** [NordicSemiconductor/Android-BLE-Library#455]
Hi,

In some cases, I receive `onDeviceConnected`  callback but `onDeviceReady` is not triggered.

Also, the `isRequiredServiceSupported` method does not call.

Turning the device Bluetooth on and off is a workaround for this, but that's not a valid solution.

**Comment by philips77** [comment]
Looks like something fails with service discovery. Do you get disconnection or an error after some time? Are you using `.retry(times, delay)` in `ConnectRequest`?

**Comment by talfsaverone** [comment]
We are not setting retry.
But we are not getting the device disconnected or any failed callback.
The devices remain connected on the Bluetooth page.

What is the recommended retry settings?

**Comment by philips77** [comment]
I'm usually using `retry(3, 100)`, so 3 times with delay 100 ms in between. Seems to be fairly stable...

**Comment by philips77** [comment]
Here's 3, 300: https://github.com/NordicSemiconductor/Android-nRF-Blinky/blob/8352e92ce2dd12af5a05a60643a64187473adbc0/blinky/ble/src/main/java/no/nordicsemi/android/blinky/ble/BlinkyManager.kt#L57

**Comment by talfsaverone** [comment]
Thanks!
