### ISSUE TITLE
Issue with Bluetooth 5.2..

### ISSUE THREAD

**Issue by karthick1611** [NordicSemiconductor/Android-BLE-Library#457]
Hi, 

As far as I tested, I believe Request MTU is not working in Bluetooth Version 5.2. 
I got MTU updated but when I write and read characteristics which is more than 20 bytes, app not working.
Did anyone noticed it?.

I tested with Samsung S22 Plus
Samsung S22 Ultra
Oppo Reno 7

These devices having Bluetooth 5.2. 

Is there anyway to increase MTU?.

When I remove MTU, by default it's taking 23 as MTU which is not good?..

**Comment by philips77** [comment]
Hi, sorry for not aswering your question earlier.

If your device supports MTU values higher than 23, the request should work. Also, since Android 13 (?) Android is always asking for MTU=517, not matter the value given to the request.

I'll close the issue as it is more than 1 year old now.
