### ISSUE TITLE
ble-gatt-client fails to start on Android 13

### ISSUE THREAD

**Issue by Slion** [NordicSemiconductor/Android-BLE-Library#458]
Looks like it's missing BLUETOOTH_CONNECT permission.
Same issue with Android 12.

**Comment by Yogurt4** [comment]
Yes. Starting from API level 31, BLUETOOTH_ADVERTISE (to be discoverable) and BLUETOOTH_CONNECT (to connect paired devices) is required.
Put them into AndroidManifest.xml and you also need to call
```
ComponentActivity.registerForActivityResult(ActivityResultContracts.RequestMultiplePermissions()) ...
```

**Comment by philips77** [comment]
Yes. It's the app's responsibility to request these permissions, not the library.
