### ISSUE TITLE
Connect request sometimes does not execute

### ISSUE THREAD

**Issue by brkalmar** [NordicSemiconductor/Android-BLE-Library#466]
Affected versions: 2.6.0

Enqueueing a `connect()` request on a manager right after the connected device had gone out of range (with `isConnected` and `isReady` both false) sometimes leads to the request not being executed at all. None of the callbacks set on the request are invoked, and the timeout does not trigger either.

If a request is enqueued successfully, I would expect it to always execute and invoke one of the callbacks. In the above described case, I would assume it would fail or time out, but even an invalid request invocation would be acceptable as long as it's consistent.

**Comment by philips77** [comment]
This might have perhaps been fixed by #522. Would be cool if you could test with 2.7 after I release the lib soon.
