### ISSUE TITLE
Galaxy S9 won't disconnect from device

### ISSUE THREAD

**Issue by lukecorbin** [NordicSemiconductor/Android-BLE-Library#47]
I am hoping to find a work around on a BLE bug using the BleManager and the GS9.

I find after a few connect/disconnect cycles that the peripheral device remains connected.

The almost unbelievable part is that toggling the BT icon on the phone does not disconnect the device.  When I restart the GS9 I can then see the device disconnect.

Perhaps you might have a more reliable way I should be disconnecting where I call disconnect() and wait for a callback to ensure the device really disconnected?

**Comment by philips77** [comment]
Hi @lukecorbin,
So my guess would be, that you have another app connected to the same device on your phone. For example, nRF Connect likes to connect in the background. But if you are working with HID device it may be the system Bluetooth app, or any other, that's using Bluetooth. Some time ago we heard rumors about Spotify app that was holding a connection. Calling `disconnect()` just closes your local virtual connection. The system will terminate the physical connection one second after the last virtual was closed.
You may actually have multiple virtual connections in your app, if you call `device.connectGatt(...)` many times. Each time you are given a new instance of `BluetoothGatt`, but they are all equally good and may be used in different parts of your app. Disconnecting form one doesn't disconnecting others.

As to the other issue. Android can even connect to BLE devices when the Bluetooth is off. It's just says it's off, while it's not fully true. Android is using it to increase location accuracy, etc. You can't scan with Bluetooth off, but connecting may be possible on some phones, including Pixels. nRF Connect doesn't allow to do this, but that's implemented behavior. And it should be enough to start Airplane Mode to make them disconnect, no need to restart.

The solution, if you really need to make the device disconnected, is to trigger the disconnection from the peripheral side. This can be done, for example, by sending some specific command from the phone and waiting for status change. 
I may to add "WaitForDisconnect" request to this library for that purpose. I have to think about it.

**Comment by philips77** [comment]
Task created in #51. Closing this one. If my above solution didn't help you, feel free to open it again.
