### ISSUE TITLE
Method name advise

### ISSUE THREAD

**Issue by tzraeq** [NordicSemiconductor/Android-BLE-Library#472]
First, Thank you for this lib.
In the version 2.6.0, there are some methods named setNotificationCallback, setIndicationCallback, setWriteCallback and setWriteCallback. 
Shouldn't they be named with a 'get' prefix?

**Comment by philips77** [comment]
Well, i get your point, as those methods return the callbacks, but by using those methods you actually set them. The callbacks aren't set until you call that method. You need to specify the behavior by using `.with` and other methods on the returned object. So, in other words, those methods return something like a builder for the callbacks that they set.
