### ISSUE TITLE
Ignore service change

### ISSUE THREAD

**Issue by talfsaverone** [NordicSemiconductor/Android-BLE-Library#473]
Is it possible to ignore the service change, and not invalidate the services?
I'm getting in the logs:
Service changed, invalidating services
Services discovered
Target initialized
onDeviceReady

My Bluetooth device causes this frequently but I want to ignore it since it uses two services and the main one does not change.

**Comment by philips77** [comment]
Hi,
A far as I remember, the Service Changed indication can contain information about handle number that have changed, but, also as far as I know, Android doesn't have any selective API and invalidates everything. Perhaps you could use the same characteristic instances, but that's not guaranteed, so you'd have to just do that on your side. Try not nullifying references in `onServiceInvalidated` and just use. But anyway, under the hood I think Android will do the full service discovery. If you have a sniffer that's worth testing

**Comment by philips77** [comment]
Hi,
A far as I remember, the Service Changed indication can contain information about handle number that have changed, but, also as far as I know, Android doesn't have any selective API and invalidates everything. Perhaps you could use the same characteristic instances, but that's not guaranteed, so you'd have to just do that on your side. Try not nullifying references in `onServiceInvalidated` and just use. But anyway, under the hood I think Android will do the full service discovery. If you have a sniffer that's worth testing
