### ISSUE TITLE
How to obtain the real bond state?

### ISSUE THREAD

**Issue by alanban** [NordicSemiconductor/Android-BLE-Library#491]
hi there
 i notice that `bluetoothDevice.getBondState()` returns whether the target device is bonded. but This does not mean that the target device also has such information.

so how do i ensure the real bond state, when the deivice is connected

**Comment by philips77** [comment]
Hello,
Sorry for the veeeery late response. I dno't think getting this information is possible. In the library we do have `ensureBond(...)` method which removes an existing bond information, if such exist, and bonds again.
