### ISSUE TITLE
Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8

### ISSUE THREAD

**Issue by hao0917** [NordicSemiconductor/Android-BLE-Library#494]
Hi :
when update library to version 2.6.1,build is fail

Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option

**Comment by philips77** [comment]
Next version of the library (2.7) will be using Java 17.
