### ISSUE TITLE
Distribution through Maven

### ISSUE THREAD

**Issue by maszhin** [NordicSemiconductor/Android-BLE-Library#5]
Hi,

Great library! It helped us a lot to set up our BLE services.

Do you have any plans for [distributing the library to Maven](https://maven.apache.org/guides/mini/guide-central-repository-upload.html)? 
It's a bit time consuming (in case of time compilation) to use your library as a module within the project.

Best regards,
Marcin

**Comment by philips77** [comment]
Hi,

Thanks. It will, eventually. Like DFU lib or scanner compat lib. I'm still adding some features before that happens.
Let's leave this issue here as a reminder.

**Comment by maszin** [comment]
Nice! Thanks.

**Comment by philips77** [comment]
Both version 1.x and 2.x (alpha) are now on jcenter/Maven.
