### ISSUE TITLE
Wrong NonNull annotations in response package

### ISSUE THREAD

**Issue by maragues-kolibree** [NordicSemiconductor/Android-BLE-Library#50]
All getters in _response_ package are annotated with NonNull, when truth is that that's not guaranteed.

In fact, in the past I have received WriteResponse's with rawData null. I think they were caused by https://github.com/NordicSemiconductor/Android-BLE-Library/issues/48, but still, it's possible

I created a PR to change annotations to Nullable
https://github.com/NordicSemiconductor/Android-BLE-Library/pull/49

I'm having CLA signing issues, I'll look into that later.

**Comment by philips77** [comment]
Released in 2.0.2.
