### ISSUE TITLE
There there a version of the library which can be used on Android 7.1.1 Nougat?

### ISSUE THREAD

**Issue by YangRongAtGit** [NordicSemiconductor/Android-BLE-Library#500]
Hello, one of our products uses a customized nrf52840 as peripherals to collect data and send the data to the central device running Android 7.1.1. The application on the Android device's API level is 25. On the Android side, we use Kotlin 1.5.2. I just wonder that is it possible for us to use the Android-BLE-Library on our central device application. Cheers.

**Comment by philips77** [comment]
Hello, sorry for the late response.

The library should work from Android 4.3 until the latest 14.
Recent versions of the app have `targetSdk` set to API 34 (Android 14) but, if needed, you may use older.
