### ISSUE TITLE
features

### ISSUE THREAD

**Issue by ilker-aktuna** [NordicSemiconductor/Android-BLE-Library#501]
This is not actually an issue, but just a question.
I am trying to set some flags on an Advertisement data for my app.
For example , LE limited Discoverable mode as seen here:

```
1A # Flags value 0x1A = 000011010  
   bit 0 (OFF) LE Limited Discoverable Mode
   bit 1 (ON) LE General Discoverable Mode
   bit 2 (OFF) BR/EDR Not Supported
   bit 3 (ON) Simultaneous LE and BR/EDR to Same Device Capable (controller)
   bit 4 (ON) Simultaneous LE and BR/EDR to Same Device Capable (Host)
```

default Android BLE library does not allow that. Can I use this library to set these flags ?
if possible, how ?
if not, could it be possible by wrapping the Advertiser part of the Android BLE library ?

**Comment by philips77** [comment]
Hello,
This library doesn't support advertising, just connection. Unfortunately, even the native API doesn't allow selling custom advertising data or flags. Flags are set automatically based on wherever the advertising is connectable or not.
