### ISSUE TITLE
Hello, I may need your help

### ISSUE THREAD

**Issue by hjjice** [NordicSemiconductor/Android-BLE-Library#505]
Hello, I want to know how your NRF Connect app is compatible or set to scan parameters. I found that a question is: setusehardwareBatchingifSupported is set to True. At this time, all mobile phones can be connected to the device, but it will not scan some Bluetooth transparent modules to FALSE, but the NRF Connect App can always scan the seconds on all mobile phones to these transmitted modules and connect to the connection. them.

**Comment by philips77** [comment]
nRF Connect scans using native API, not the Scanner Compat library. It' as if the `setUseHardwareBatchingIfSupported` was set to true, but batching is not used at all. The app sets delay report to 0 and batches in the app.
