### ISSUE TITLE
attachClientConnection problem on Android 10 devices.

### ISSUE THREAD

**Issue by nadrolinux** [NordicSemiconductor/Android-BLE-Library#506]
Hi,
I have a problem with new `attachClientConnection` method. When I replace `attachClientConnection` by `connect` like in Trivia example all works fine. I use following phones:
P6 - Pixel 6 (stock Android 13)
P6a - Pixel 6a (stock Android 13)
MI8 - Xiaomi MI8 (stock Android 10)
MT - Motorola Moto E 2015 LTE (LineageOS Android 10)
How to reproduce the problem:
1. Start server on P6, P6a or MI8 (MT doesn't support Multiple Advertisement). It's irrelevant which phone I use as a server.
2. Join all other phones to the server.
3. Close a server via standard `close`.
4. Only both Pixel phones receives `onDeviceDisconnected` callback. On clients like a MI8 and MT callback isn't triggered. I have to disable BT from the system menu on the server to obtain `onDeviceDisconnected` on MI8 and MT clients or manually disconnect clients from the server. It looks like a calling `disconnect().enqueue()` from the server doesn't work in some cases when `attachClientConnection` is used, however all `disconnect` calls returned Success callback. Maybe I use `attachClientConnection` in a wrong way and it's not a bug, however it's interesting that it works in a different way on some phones.

Cheers,
Patryk

**Comment by philips77** [comment]
I'm looking into that. Thank you for the report.
