### ISSUE TITLE
Send data over 10k charcter

### ISSUE THREAD

**Issue by Jatindersyall12** [NordicSemiconductor/Android-BLE-Library#513]
Hi

Your's library is not working when try to send 10k data over it. Can you please assist me

Thanks 
@philips77

**Comment by Jatindersyall12** [comment]
@philips77

**Comment by philips77** [comment]
Hello, sorry I was busy with other tasks.

It should not matter how much data you want to send. How are you sending the data? 
What is the MTU? 
What are the symptoms you're getting?

We're using this library in nRF Connect Device Manager library to send much larger files.
