### ISSUE TITLE
Devices are not reconnecting after upgrade from 2.6.1 to 2.7.0

### ISSUE THREAD

**Issue by corentin-c** [NordicSemiconductor/Android-BLE-Library#526]
Hi,

After we upgraded from 2.6.1 to 2.7.0, when using connect with autoConnect true,  devices are not reconnecting  after the first disconnection.

We use client and server with `clientManager.useServer(serverManager)`
After debugging what I understand is happening in our code is :

- In 2.6.1 : 
On disconnection, **server** manager `onConnectionStateChanged `is triggered
It **does not call** `notifyDeviceDisconnected `in this version
**client** manager `onConnectionStateChanged `is triggered. 
This set the variable `wasConnected `to the value of `connected `which is **true**
**calls** `internalConnect `because `wasConnected `is true and that will make the device autoconnect in the future

- In 2.7.0
On disconnection, **server** manager `onConnectionStateChanged `is triggered
This **now calls** `notifyDeviceDisconnected `that sets `connected `to false
**client** manager `onConnectionStateChanged `is triggered. 
This set the variable `wasConnected `to the value of `connected `which is **false**
**Does not call** `internalConnect `because `wasConnected `is false and that **will not** make the device autoconnect in the future

Is this a bug, or are we using the library wrong in some way ?

Thanks.

**Comment by philips77** [comment]
Let me check. Thank you for the report.

**Comment by philips77** [comment]
...and I'm not sure how to fix it. Need to think.

**Comment by corentin-c** [comment]
confirmed fixed on 2.7.1
