### ISSUE TITLE
Question about support of this lib and the new one

### ISSUE THREAD

**Issue by BurgerSzilard** [NordicSemiconductor/Android-BLE-Library#532]
Hi. 

I would like to know until when will this library be supported ? I saw that you started to work on a new one. 
Which library should be used ? Which one is more stable / contains more features ?

Thanks a lot for the great work you do.

**Comment by philips77** [comment]
Hello,
We wil only do bug fixing releases to this one, but it's pretty much feature complete.
The new one is better, as it is designed with tests in mind and built on coroutines, but it's still in somewhat early stage, so may contain some bugs.
