### ISSUE TITLE
Is there any adaptation for Android 14?

### ISSUE THREAD

**Issue by ZouZLong** [NordicSemiconductor/Android-BLE-Library#533]
Is there any adaptation for Android 14?

**Comment by philips77** [comment]
The library is working on Android 14. What would you expect more?

**Comment by ZouZLong** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
