### ISSUE TITLE
Catch SecurityException from setCharacteristicNotification

### ISSUE THREAD

**Issue by philips77** [NordicSemiconductor/Android-BLE-Library#538]
Ref.: https://github.com/NordicSemiconductor/Android-BLE-Library/pull/518#issuecomment-1825487544

**Comment by AuriR** [comment]
@philips77 What is the status of this PR, please? It seems a user toggle of Bluetooth or restart of the device - true on many newer Pixel devices - is required. This leads to a poor user experience. Has a priority been set on this, please? Or perhaps Google Pixels don't use Nordic chipsets, and I'm barking up the wrong tree? Thanks in advance!

**Comment by philips77** [comment]
Hello,
I'm busy with other projects at the moment. Could you, please, create a PR which I could quickly merge and release?
