### ISSUE TITLE
Ask a question, thank you

### ISSUE THREAD

**Issue by FZ985** [NordicSemiconductor/Android-BLE-Library#546]
Hello, I am new to Bluetooth development and I don’t understand some things very well. Can the app connect to multiple devices at the same time, such as multiple blood glucose meter devices? The uuid of the blood glucose meters are all the same. Can it be connected and monitored at the same time?

**Comment by Fly-Felix** [comment]
用List来管理BleManager就可以了

**Comment by philips77** [comment]
When it comes to this library, you may create a `BleManager` instance per each connected device and keep them in a list or something alike.
