### ISSUE TITLE
Want to get the characteristic on which the data was received for the characteristics I have subscribed to get notified for

### ISSUE THREAD

**Issue by xaviergspintly** [NordicSemiconductor/Android-BLE-Library#547]
I am subscribing to some characteristics using the `enableNotifications()` and I receive the data using a `DataReceivedCallback` .
That works fine.
However, I want to now also know on which particular characteristic object or characteristic UUID I'm getting the notification (meaning characteristic on which I'm getting the data in `DataReceivedCallback`).
Is there something similar to `DataReceivedCallback` which I can use to know this?

**Comment by philips77** [comment]
You may register one callback per characteristic, so you'll know it by just having different implementations.

**Comment by xaviergspintly** [comment]
Yeah. I kind of did the same afterwards but forgot to close this issue. Thanks.
