### ISSUE TITLE
Question: Will this allow me to send HCI Level Commands?

### ISSUE THREAD

**Issue by meakashrao** [NordicSemiconductor/Android-BLE-Library#553]
I face a problem with BLE 4.2 and we are exploring the option of updating the channel map from an APP after the connection is established because in our case, an Android App works as Master. 

The specific command I am looking for is: HCI_LE_Set_Host_Channel_Classification

If yes, please let me know how and where can I trigger this from.

**Comment by philips77** [comment]
Android does not provide any API for sending HCI commands directly. Updating channel map is not possible form the application.
