### ISSUE TITLE
OTA upgrade problem

### ISSUE THREAD

**Issue by 18254819000** [NordicSemiconductor/Android-BLE-Library#559]
Does it support OTA upgrade for multiple Bluetooth devices at the same time？？

**Comment by philips77** [comment]
Hello,
This library does not provide the functionality of upgrading devices, just the base GATT connectivity. It supports multiple simultaneous connections.
If you're asking reg our DFU (OTA upgrade) libraries, the old one (Android DFU Library) is built on an `IntentService`, which will queue invocations and run one by one. On the other hand, the DFU library for nRF Connect SDK and Zephyr based devices - nRF Connect Device Manager lib - should allow simultaneous upgrades, as it just provides the transport, without any service or work manager.
