### ISSUE TITLE
Issue with auto connect

### ISSUE THREAD

**Issue by talfsaverone** [NordicSemiconductor/Android-BLE-Library#566]
When using autoConnect(true) on the connect request sometimes it does not auto-connect, even though the devices are near and the OS is connected.

**Comment by philips77** [comment]
Auto connect does not work with private random resolvable addresses for unbonded devices. 
Do you know what type of address is the device advertising with?

**Comment by philips77** [comment]
Also, since version 2.8.0 it is possible to use auto-connect from the first attempt using #575.

**Comment by philips77** [comment]
I'm closing due to long time of inactivity.
