### ISSUE TITLE
Scan Result Question

### ISSUE THREAD

**Issue by KevinMartinezC** [NordicSemiconductor/Android-BLE-Library#572]
I have a question regarding the disconnect device functionality. 
If I connect the device and then disconnect it, why is it not visible in the scan results again?

```kotlin
override fun disconnectDevice() {
   disconnect().enqueue()
}
```
    
and why i get the result just in the `onBatchScanResults` and not the `onScanResult`? 
```kotlin    
override fun onScanResult(callbackType: Int, result: ScanResult) {
            
}
        
override fun onBatchScanResults(results: List<ScanResult>) {
   val newResults = results.filter { it.isConnectable }
}
```

**Comment by philips77** [comment]
Hello,
On Android (and iOS) a device may be connected by multiple `BluetoothGatt` objects (or `CBPeripheral` on iOS). The system manages the physical connection, and each such client acts independently. If one gest disconnected it gets disconnected event, but that doesn't mean, that the device actually got disconnected, as other clients may still be connected to it. Only when the last client disconnects, and nothing else reconnects within a second, the OS terminates the physical connection.

To make sure that your device disconnects you need to implement some command, which you send to some characteristic, which triggers disconnection from the device side.

> and why i get the result just in the onBatchScanResults and not the onScanResult?

When you use [`setReportDelay`](https://developer.android.com/reference/android/bluetooth/le/ScanSettings.Builder#setReportDelay(long)) with a value > 0, the results will be batched, and the other method is used. Works kinda-reliable with delays > 5 seconds. Use 0 if you want to be notified immediately using `onScanResult`.
