### ISSUE TITLE
A little optimization in HeaderBasedPacketMerger

### ISSUE THREAD

**Issue by haogev6** [NordicSemiconductor/Android-BLE-Library#585]
https://github.com/NordicSemiconductor/Android-BLE-Library/blob/331fee93215c6bbc215e8471e389bfb40f3e5ed4/test/src/main/java/no/nordicsemi/andorid/ble/test/spec/HeaderBasedPacketMerger.kt#L33-L42

This snippet could be refactored to codes below:
```
ByteArray(buffer.remaining()) 
   .apply { buffer.get(this) } 
   .also { output.write(it) } 
return receivedDataSize - 2 == expectedSize
 ```

**Comment by philips77** [comment]
Thanks! Merged.
