### ISSUE TITLE
Simpler tutorial/example

### ISSUE THREAD

**Issue by beegee-tokyo** [NordicSemiconductor/Android-BLE-Library#72]
Sorry to bother, as this is not really an issue.

I am not a super experienced programmer for Java but was able to write an app to communicate with a nRF52832 that has a custom characteristic. I have a working code using BlueroothLeService.java that is used in many examples/tutorials but have some performance issues with it. 

I tried to use the nRF Toolbox and nRF Blinky code to get an idea how to use this library but they are very difficult (code scattered over several fragments/activities or using specific BlinkyViewMode).

Is there any simple code example that shows how to connect to a device, connect to the characteristic, enable notifications and receive/send data? 

Thanks for any link and help.

**Comment by philips77** [comment]
The usage of BLE Library in nRF Blinky is very simple. It's just one class: https://github.com/NordicSemiconductor/Android-nRF-Blinky/blob/master/app/src/main/java/no/nordicsemi/android/blinky/profile/BlinkyManager.java
The BLE Manager is responsible for managing a single connection. It should expose API that can be used by other classes, for example the one above has '`send(boolean)` method. The callbacks from the device (in case of Blinky a callback is called when used clicks a button on the DevKit) are in [this](https://github.com/NordicSemiconductor/Android-nRF-Blinky/tree/master/app/src/main/java/no/nordicsemi/android/blinky/profile/callback) package and they are called directly from the Ble Manager linked above.

BLE Manager may be used in a Service, from ViewModel, or directly in the activity if you are not scared of orientation changes and memory leaking, etc. The remaining classes of nRF Blinky are responsible for scanning or UI and are not needed to understand how to use BLE Library.

**Comment by Billideveloper** [comment]
how to get connection state update and how to discover service and how to notify
