### ISSUE TITLE
Rename onLinklossOccur to onLinklossOccurred?

### ISSUE THREAD

**Issue by tamberg** [NordicSemiconductor/Android-BLE-Library#8]
Consider renaming onLinklossOccur [0] to onLinklossOccurred for consistency.

[0] https://github.com/NordicSemiconductor/Android-BLE-Library/blob/master/ble/src/main/java/no/nordicsemi/android/ble/BleManagerCallbacks.java#L73

**Comment by philips77** [comment]
True. Will do it.
Check out the develop branch. I'm doing many changes there. API will be improved. I'm trying it to be backwards compatible, at least with some deprecations, but for sure some packages names will change.

**Comment by tamberg** [comment]
Oops, should be onLink*L*ossOccurred, otherwise AndroidStudio still warns about "typo".

**Comment by philips77** [comment]
Sure thing.
