### ISSUE TITLE
Issues importing library into Xamarin Forms C#

### ISSUE THREAD

**Issue by sdinnes** [NordicSemiconductor/Android-BLE-Library#84]
I am attempting to use this library in a Xamarin Forms C# project; you can bind a Java library to an Android .Net assembly using a special project type in Visual Studio.  This process usually involves doing some tweaking to the bindings using a project xml file included in the VS project.

I have managed to fix several binding issues but have come up against one that has so far defeated me: in the error list, I get many errors of the type

The type 'ConnectRequest' already contains a definition for 'cb_timeout_J'

My analysis has led me to believe that it is a result of class TimeoutableRequest (which is abstract) and descendant class ConnectRequest both having method "timeout".  Although declared override in ConnectRequest, it seems the bindings are mapping it twice, leading to the above errors.

I have  tried renaming the method and the parameter names, to no avail.

Do you have any tips for getting this working?

**Comment by philips77** [comment]
Hmm... I see the `@IntRange(from = 0)` was missing in `timeout(long)` in `ConnectRequest` and `TimeoutableValueRequest` classes, did you try adding it? Perhaps the signature wasn't exact?
That is the only thing that differs `timeout` from any other method that also is overridden in `ConnectRequest`.

**Comment by sdinnes** [comment]
Thanks for the feedback!  Late last night I found what I think is the solution; I'm working on testing it out now in a test app.

I had noticed that TimeoutableRequest had no visibility qualifier, whereas Request and ConnectRequest are both public.  I tried fixing this in the metadata.xml to no avail, so finally I did what I'd wanted to avoid, and changed the java - only adding the public qualifier to TimeoutableRequest.  This immediately fixed all of the binding errors!

I think the clue was in the generated C#, it showed ConnectRequest as being directly descended from Request, omitting TimeoutableRequest entirely.  (In C# there are strict rules about descendant visibility).

I'll post an update later today hopefully on whether this fixed the issue.

**Comment by philips77** [comment]
I could make the middle classes public if it helps. Please share your results.

**Comment by sdinnes** [comment]
Thanks for the feedback!  Late last night I found what I think is the solution; I'm working on testing it out now in a test app.

I had noticed that TimeoutableRequest had no visibility qualifier, whereas Request and ConnectRequest are both public.  I tried fixing this in the metadata.xml to no avail, so finally I did what I'd wanted to avoid, and changed the java - only adding the public qualifier to TimeoutableRequest.  This immediately fixed all of the binding errors!

I think the clue was in the generated C#, it showed ConnectRequest as being directly descended from Request, omitting TimeoutableRequest entirely.  (In C# there are strict rules about descendant visibility).

I'll post an update later today hopefully on whether this fixed the issue.

**Comment by sdinnes** [comment]
In the end I only had to do that one change, all else was just getting to grips with general Java binding issues.  The new library works massively better than any I used previously!

In time, I may put an example project up on GitHub and, subject to management approval in my company, may attempt to create a NuGet package for this for use in Visual Studio.

**Comment by lfongaroScp** [comment]
@sdinnes Did you manage to bind this library with Xamarin?
Is your code public available?

Thank you

**Comment by sdinnes** [comment]
@lfongaroScp - thanks for the reminder!  I have a sample Xamarin Forms project which includes the bound libraries (scanner and connect) and demonstrates how to use them with some simple iBeacon BLE commands.  As this derives from a commercial product I work on for my employer, I need to obtain their approval before I make it public.  Watch this space!

**Comment by sdinnes** [comment]
@lfongaroScp - I have made my repo public:

[https://github.com/sdinnes/NordicAndroidBle](url)

**Comment by geervani** [comment]
@sdinnes [this](https://github.com/sdinnes/NordicAndroidBle) link is broken.

**Comment by philips77** [comment]
I fixed the link.
