### ISSUE TITLE
write request took much time

### ISSUE THREAD

**Issue by ymwcoding** [NordicSemiconductor/Android-BLE-Library#90]
Hi,
 i want to write data to the ble device as quickly as possible.
Below is the code which i use.

pubic void phoneWriteData()
{
   byte[] bytes = new byte[mtuSize -3];// mtu is 251
   Log.i(TAG, "write");
   writeCharacteristic(characteristic, bytes)
          .with((device,data) -> {
          Log.i(TAG, "with");
           phoneWriteData();
           }
          .enqueue();
}

Log info show :"write" 13:33:061   "with" 13:33:068
it took 7ms to write a packet data， connect interval of my ble device is 7.5ms, only one packet can be sent in  a interval. it's too slow.

**Comment by philips77** [comment]
If you're using Write Without Response, the callback is called when the data were added to the outgoing queue, not when they were physically sent to the device.
When you use the default write type (write with response), it will be much slower (just one packet per connection interval) and callbacks are called when the data are confirmed by the target device.
