### ISSUE TITLE
no.nordicsemi.android:dfu:1.9.0导入错误

### ISSUE THREAD

**Issue by qx-mark-wu** [NordicSemiconductor/Android-BLE-Library#96]
我新建一个项目之后先是把no.nordicsemi.android:dfu:1.9.0导入项目报了以下错误：
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.1.0-alpha04] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-20:19 to override.

我按错误提示把'tools:replace="android:appComponentFactory"'添加到Manifest的<application>标签里
但是发现还是存在下面这个错误
Manifest merger failed with multiple errors, see logs

请问是什么原因呢？

**Comment by philips77** [comment]
Use version 1.8.1 or migrate your project to Android Jetpack.
