### ISSUE TITLE
Stuck after Status 8 when writing to a characteristic on Android 9

### ISSUE THREAD

**Issue by Maragues** [NordicSemiconductor/Android-BLE-Library#97]
Hi, I sometimes get connectionStatus=8 when writing to a characteristic

> Writing characteristic 03... (WRITE COMMAND)
> gatt.writeCharacteristic(03...)
> 
> //6 seconds gap
>
> BluetoothGatt: onClientConnectionState() - status=8 clientIf=7 device=C0:4B:3C:5D:93:49
> [Callback] Connection state changed with status: 8 and new state: 0 (DISCONNECTED)
> Error: (0x8): GATT CONN TIMEOUT
> Connection lost
> onDeviceDisconnected()
> fail for command 0x39 with status 8 //WriteRequest callback

I don't know the root cause, might be a bug in our end. It's only happening in some Android 9 devices (Pixel 2, for example)

The thing is, once this happens, I stop receiving `onCharacteristicWriteSafe` callback for future writes. Even when the write succeeds (I know thanks to internal logs), I don't get the callback.

Any hint as to why this might be happening in Android 9? 

PS. I know this is more a stackoverflow question, but there's no specific tag for this library. If you considered subscribing to it, perhaps we could create one, add it to the readme and stop polluting the issues here.

**Comment by philips77** [comment]
That's really weird, as you are using WRITE COMMAND, so the callback should just be called immediately after the packet is added to the outgoing queue (unless it's full).
Did you take any sniffer logs, for example using hci-logs on Android?

I agree that this is more a StackOverflow question, or at least for [DevZone](https://devzone.nordicsemi.com/), if you are using Nordic chips. I will gladly add the tag information on the Readme if you create a tag on SO. I still need some more point sot be able to create tags.

**Comment by Maragues** [comment]
I posted a question on SO with the tag https://stackoverflow.com/questions/55356006/bluetooth-oncharacteristicwrite-not-invoked-after-status-8-when-writing-to-a-cha

**Comment by Maragues** [comment]
On the question, I don't modify the Write type, and it works for some writes, then it's stuck.

My impression is it's a bug in our firmware, I'll update this issue with more information if it turns out it isn't
